/**
 * LangGraph Orchestrator Package
 *
 * Orchestration runtime, graph definitions, and adapters for agent workflows.
 */

/** Package version - matches package.json */
export const version = '0.0.1'

// Config module exports - model assignments and LLM provider
export {
  // Model Assignments
  ClaudeModelSchema,
  OllamaModelSchema,
  ModelSchema,
  ModelAssignmentsSchema,
  type ClaudeModel,
  type OllamaModel,
  type Model,
  type ModelProvider,
  type ParsedOllamaModel,
  type ModelAssignments,
  getModelProvider,
  isOllamaModel,
  isClaudeModel,
  parseOllamaModel,
  DEFAULT_MODEL_ASSIGNMENTS,
  loadModelAssignments,
  clearModelAssignmentsCache,
  getModelForAgent,
  getAgentsForModel,
  hasModelAssignment,
  MODEL_SELECTION_CRITERIA,
  suggestModel,
  // LLM Provider
  LLMProviderConfigSchema,
  type LLMProviderConfig,
  loadLLMProviderConfig,
  clearLLMProviderConfigCache,
  isOllamaAvailable,
  clearOllamaAvailabilityCache,
  createOllamaLLM,
  clearOllamaLLMCache,
  getLLMForAgent,
  getModelInfoForAgent,
  type LLMResult,
} from './config/index.js'

// State module exports - GraphState schemas, types, and utilities
export {
  // Enum schemas and types
  ArtifactTypeSchema,
  type ArtifactType,
  ARTIFACT_TYPES,
  RoutingFlagSchema,
  type RoutingFlag,
  ROUTING_FLAGS,
  GateTypeSchema,
  type GateType,
  GATE_TYPES,
  GateDecisionSchema,
  type GateDecision,
  GATE_DECISIONS,
  // Story state (FLOW-SYNC)
  StoryStateSchema,
  type StoryState,
  STORY_STATES,
  isTerminalState,
  isActiveState,
  isWorkableState,
  getNextState,
  isRecoveryState,
  // Reference schemas and types
  EvidenceRefSchema,
  EvidenceTypeSchema,
  type EvidenceRef,
  type EvidenceType,
  NodeErrorSchema,
  type NodeError,
  type NodeErrorInput,
  // Main GraphState schema and types
  GraphStateSchema,
  StateSnapshotSchema,
  StateSnapshotStateSchema,
  GRAPH_STATE_SCHEMA_VERSION,
  type GraphState,
  type GraphStateInput,
  type StateSnapshot,
  type StateSnapshotState,
  // Validation utilities
  validateGraphState,
  safeValidateGraphState,
  createInitialState,
  isValidGraphState,
  type ValidationResult,
  type CreateInitialStateParams,
  // State utilities
  diffGraphState,
  serializeState,
  deserializeState,
  safeDeserializeState,
  cloneState,
  type PropertyDiff,
  type StateDiff,
} from './state/index.js'

// Runner module exports - node factory, retry, timeout, error handling
export {
  // Node factory
  createNode,
  createSimpleNode,
  createLLMNode,
  createLLMPoweredNode,
  createToolNode,
  type NodeFunction,
  type NodeImplementation,
  type LLMNodeImplementation,
  type LLMPoweredNodeConfig,
  type LLMRunnableConfig,
  // Retry logic
  withNodeRetry,
  calculateRetryDelay,
  createRetryWrapper,
  wouldRetry,
  type RetryOptions,
  type RetryResult,
  // Timeout handling
  withTimeout,
  withTimeoutResult,
  createTimeoutController,
  type TimeoutOptions,
  type TimeoutResult,
  // Error classes and constants
  NodeTimeoutError,
  NodeCancellationError,
  NodeCircuitOpenError,
  NodeRetryExhaustedError,
  NodeExecutionError,
  NodeErrorCodes,
  NodeErrorMessages,
  normalizeError,
  sanitizeStackTrace,
  type NodeErrorCode,
  type StackSanitizationConfig,
  // Error classification
  isRetryableNodeError,
  classifyError,
  getErrorCategory,
  type ErrorClassification,
  type ErrorCategory,
  // State helpers
  updateState,
  updateArtifactPaths,
  updateRoutingFlags,
  updateGateDecisions,
  addEvidenceRefs,
  addErrors,
  createNodeError,
  createErrorUpdate,
  createBlockedUpdate,
  createCompleteUpdate,
  mergeStateUpdates,
  type StateUpdate,
  type CreateNodeErrorOptions,
  // Logger
  createNodeLogger,
  createNodeLoggerWithContext,
  type NodeLogger,
  // Circuit breaker
  NodeCircuitBreaker,
  type CircuitBreakerStatus,
  type CircuitState,
  // Configuration types
  NodeConfigSchema,
  NodeRetryConfigSchema,
  CircuitBreakerConfigSchema,
  NodeExecutionContextSchema,
  DEFAULT_RETRY_CONFIG,
  DEFAULT_CIRCUIT_BREAKER_CONFIG,
  RETRY_PRESETS,
  generateTraceId,
  generateGraphExecutionId,
  createNodeExecutionContext,
  type NodeConfig,
  type NodeConfigInput,
  type NodeRetryConfig,
  type NodeRetryConfigInput,
  type CircuitBreakerConfig,
  type CircuitBreakerConfigInput,
  type NodeExecutionContext,
  type NodeExecutionContextInput,
  type OnRetryAttemptCallback,
  type OnTimeoutCallback,
  // Metrics (WRKF-1021)
  createNodeMetricsCollector,
  MetricsErrorCategorySchema,
  NodeMetricsCollector,
  NodeMetricsSchema,
  SerializedMetricsSchema,
  ThresholdConfigSchema,
  type MetricsErrorCategory,
  type NodeMetrics,
  type NodeMetricsCollectorConfig,
  type OnFailureRateThresholdCallback,
  type OnLatencyThresholdCallback,
  type SerializedMetrics,
  type ThresholdConfig,
} from './runner/index.js'

// Artifacts module exports - evidence-first YAML artifact schemas
export {
  // Checkpoint - tracks current phase for resume
  CheckpointSchema,
  PhaseSchema,
  createCheckpoint,
  advanceCheckpoint,
  type Checkpoint,
  type Phase,
  // Scope - defines what surfaces the story touches
  ScopeSchema,
  createScope,
  inferScopeFromContent,
  inferRiskFlags,
  type Scope,
  // Plan - structured implementation plan
  PlanSchema,
  PlanStepSchema,
  FileChangeSchema,
  CommandSchema,
  AcceptanceCriteriaMapSchema,
  createPlan,
  type Plan,
  type PlanStep,
  type FileChange,
  type Command,
  type AcceptanceCriteriaMap,
  // Knowledge Context - lessons learned and ADRs
  KnowledgeContextSchema,
  LessonSchema,
  AdrSchema,
  HighCostOperationSchema,
  createKnowledgeContext,
  type KnowledgeContext,
  type Lesson,
  type Adr,
  type HighCostOperation,
  // Evidence - single source of truth for implementation (v2 with E2E support)
  EvidenceSchema,
  EvidenceItemSchema,
  AcceptanceCriteriaEvidenceSchema,
  TouchedFileSchema,
  CommandRunSchema,
  EndpointExercisedSchema,
  TokenSummarySchema,
  // E2E Tests (v2 - ADR-006)
  E2ETestsSchema,
  ConfigIssueSchema,
  ConfigIssueTypeSchema,
  FailedE2ETestSchema,
  // Evidence functions
  createEvidence,
  updateAcEvidence,
  addTouchedFile,
  addCommandRun,
  allAcsPassing,
  getMissingAcs,
  // E2E helpers (v2)
  createE2ETests,
  addE2ETests,
  addConfigIssue,
  // Evidence types
  type Evidence,
  type EvidenceItem,
  type AcceptanceCriteriaEvidence,
  type TouchedFile,
  type CommandRun,
  type EndpointExercised,
  type TokenSummary,
  // E2E Types (v2)
  type E2ETests,
  type ConfigIssue,
  type ConfigIssueType,
  type FailedE2ETest,
  // Review - aggregated code review results
  ReviewSchema,
  FindingSchema,
  WorkerResultSchema,
  RankedPatchSchema,
  createReview,
  addWorkerResult,
  carryForwardWorker,
  generateRankedPatches,
  type Review,
  type Finding,
  type WorkerResult,
  type RankedPatch,
  // QA Verify - QA verification results
  QaVerifySchema,
  AcVerificationSchema,
  TestResultsSchema,
  QaIssueSchema,
  createQaVerify,
  qaPassedSuccessfully,
  generateQaSummary,
  addAcVerification,
  calculateVerdict,
  type QaVerify,
  type AcVerification,
  type TestResults,
  type QaIssue,
  // Story - story artifact schema (FLOW-SYNC)
  StoryArtifactSchema,
  StoryTypeSchema,
  PriorityLevelSchema,
  SurfaceTypeSchema,
  StoryAcceptanceCriterionSchema,
  StoryRiskSchema,
  StoryScopeSchema as StoryArtifactScopeSchema,
  createStoryArtifact,
  updateStoryState as updateStoryArtifactState,
  setStoryBlocked,
  addAcceptanceCriterion,
  addStoryRisk,
  isStoryBlocked,
  isStoryComplete,
  isStoryWorkable,
  getStoryNextState,
  type StoryArtifact,
  type StoryArtifactInput,
  type StoryType,
  type PriorityLevel,
  type SurfaceType,
  type StoryAcceptanceCriterion,
  type StoryRisk,
  type StoryScope as StoryArtifactScope,
} from './artifacts/index.js'

// Database module exports - repositories for persistence (FLOW-SYNC)
export {
  // Story Repository
  StoryRepository,
  createStoryRepository,
  StoryRowSchema,
  StateTransitionSchema,
  type DbClient,
  type StoryRow,
  type StateTransition,
  // Workflow Repository
  WorkflowRepository,
  createWorkflowRepository,
  // Story Transition Service (AUDIT-2 artifact gate)
  StoryTransitionService,
  ArtifactGateError,
  createStoryTransitionService,
  ElaborationRecordSchema,
  PlanRecordSchema,
  VerificationRecordSchema,
  ProofRecordSchema,
  TokenUsageRecordSchema,
  TokenUsageInputSchema,
  type ElaborationRecord,
  type PlanRecord,
  type VerificationRecord,
  type ProofRecord,
  type TokenUsageRecord,
  type TokenUsageInput,
} from './db/index.js'

// Graphs module exports - V2 agentic graph compositions
export {
  createDevImplementV2Graph,
  DevImplementV2GraphConfigSchema,
  afterDevImplementGate,
  type DevImplementV2GraphConfig,
  type DevImplementV2State,
  createPlanRefinementV2Graph,
  PlanRefinementV2GraphConfigSchema,
  afterPostconditionGate,
  type PlanRefinementV2GraphConfig,
  type PlanRefinementV2State,
  createQAVerifyV2Graph,
  QAVerifyV2GraphConfigSchema,
  afterQaGate,
  type QAVerifyV2GraphConfig,
  type QAVerifyV2State,
  createReviewV2Graph,
  ReviewV2GraphConfigSchema,
  afterReviewGate,
  type ReviewV2GraphConfig,
  type ReviewV2State,
  createStoryGenerationV2Graph,
  StoryGenerationV2GraphConfigSchema,
  type StoryGenerationV2GraphConfig,
} from './graphs/index.js'

// Persistence module exports - YAML artifact bridge (FLOW-SYNC)
export {
  // Surface Normalizer
  YamlSurfaceTypeSchema,
  NormalizedSurfaceTypeSchema,
  YamlScopeTouchesSchema,
  NormalizedScopeTouchesSchema,
  YamlPlanSliceSchema,
  NormalizedPlanSliceSchema,
  SurfaceNormalizerConfigSchema,
  normalizeSurfaceType,
  denormalizeSurfaceType,
  normalizeSurfaces,
  denormalizeSurfaces,
  isYamlShortForm,
  normalizeScopeTouches,
  denormalizeScopeTouches,
  normalizePlanSlice,
  denormalizePlanSlice,
  createSurfaceNormalizer,
  surfaceNormalizer,
  type YamlSurfaceType,
  type NormalizedSurfaceType,
  type YamlScopeTouches,
  type NormalizedScopeTouches,
  type YamlPlanSlice,
  type NormalizedPlanSlice,
  type SurfaceNormalizerConfig,
  // Path Resolver
  StoryStageSchema,
  YamlArtifactTypeSchema,
  ResolvedPathSchema,
  PathResolverConfigSchema,
  PathResolver,
  createPathResolver,
  inferFeatureFromStoryId,
  isValidStoryId,
  normalizeStage,
  type StoryStage,
  type YamlArtifactType,
  type ResolvedPath,
  type PathResolverConfig,
  // YAML Artifact Reader
  ClaudeStoryYamlSchema,
  ClaudeElaborationYamlSchema,
  ClaudePlanYamlSchema,
  ClaudeVerificationYamlSchema,
  ClaudeContextYamlSchema,
  YamlReaderConfigSchema,
  YamlArtifactReader,
  createYamlArtifactReader,
  type ClaudeStoryYaml,
  type ClaudeElaborationYaml,
  type ClaudePlanYaml,
  type ClaudeVerificationYaml,
  type ClaudeContextYaml,
  type YamlReaderConfig,
  type YamlReadResult,
  type StoryArtifactsReadResult,
  // YAML Artifact Writer
  YamlWriterConfigSchema,
  YamlArtifactWriter,
  createYamlArtifactWriter,
  type YamlWriterConfig,
  type YamlWriteResult,
  // YAML Artifact Bridge
  SyncDirectionSchema,
  ConflictStrategySchema,
  YamlArtifactBridgeConfigSchema,
  YamlArtifactBridge,
  createYamlArtifactBridge,
  type SyncDirection,
  type ConflictStrategy,
  type YamlArtifactBridgeConfig,
  type ArtifactSyncResult,
  type StorySyncResult,
  type BridgeLoadResult,
} from './persistence/index.js'

// Services module exports - high-level service wrappers (INFR-0020)
export {
  // ArtifactService - high-level artifact read/write service
  ArtifactService,
  createArtifactService,
  // Configuration and result types
  ArtifactServiceConfigSchema,
  ArtifactReadResultSchema,
  ArtifactWriteResultSchema,
  STAGE_SEARCH_ORDER,
  type ArtifactServiceConfig,
  type ArtifactReadResult,
  type ArtifactWriteResult,
  type StageSearchOrder,
} from './services/artifact-service.js'

// Models module exports - unified model interface and router (WINT-0230)
export { ModelRouter, ModelRouterFactory } from './models/unified-interface.js'
