/**
 * LangGraph Orchestrator Package
 *
 * Orchestration runtime, graph definitions, and adapters for agent workflows.
 */

/** Package version - matches package.json */
export const version = '0.0.1'

// State module exports - GraphState schemas, types, and utilities
export {
  // Enum schemas and types
  ArtifactTypeSchema,
  type ArtifactType,
  ARTIFACT_TYPES,
  RoutingFlagSchema,
  type RoutingFlag,
  ROUTING_FLAGS,
  GateTypeSchema,
  type GateType,
  GATE_TYPES,
  GateDecisionSchema,
  type GateDecision,
  GATE_DECISIONS,
  // Reference schemas and types
  EvidenceRefSchema,
  EvidenceTypeSchema,
  type EvidenceRef,
  type EvidenceType,
  NodeErrorSchema,
  type NodeError,
  type NodeErrorInput,
  // Main GraphState schema and types
  GraphStateSchema,
  StateSnapshotSchema,
  StateSnapshotStateSchema,
  GRAPH_STATE_SCHEMA_VERSION,
  type GraphState,
  type GraphStateInput,
  type StateSnapshot,
  type StateSnapshotState,
  // Validation utilities
  validateGraphState,
  safeValidateGraphState,
  createInitialState,
  isValidGraphState,
  type ValidationResult,
  type CreateInitialStateParams,
  // State utilities
  diffGraphState,
  serializeState,
  deserializeState,
  safeDeserializeState,
  cloneState,
  type PropertyDiff,
  type StateDiff,
} from './state/index.js'

// Runner module exports - node factory, retry, timeout, error handling
export {
  // Node factory
  createNode,
  createSimpleNode,
  createLLMNode,
  createToolNode,
  type NodeFunction,
  type NodeImplementation,
  // Retry logic
  withNodeRetry,
  calculateRetryDelay,
  createRetryWrapper,
  wouldRetry,
  type RetryOptions,
  type RetryResult,
  // Timeout handling
  withTimeout,
  withTimeoutResult,
  createTimeoutController,
  type TimeoutOptions,
  type TimeoutResult,
  // Error classes and constants
  NodeTimeoutError,
  NodeCancellationError,
  NodeCircuitOpenError,
  NodeRetryExhaustedError,
  NodeExecutionError,
  NodeErrorCodes,
  NodeErrorMessages,
  normalizeError,
  sanitizeStackTrace,
  type NodeErrorCode,
  type StackSanitizationConfig,
  // Error classification
  isRetryableNodeError,
  classifyError,
  getErrorCategory,
  type ErrorClassification,
  type ErrorCategory,
  // State helpers
  updateState,
  updateArtifactPaths,
  updateRoutingFlags,
  updateGateDecisions,
  addEvidenceRefs,
  addErrors,
  createNodeError,
  createErrorUpdate,
  createBlockedUpdate,
  createCompleteUpdate,
  mergeStateUpdates,
  type StateUpdate,
  type CreateNodeErrorOptions,
  // Logger
  createNodeLogger,
  createNodeLoggerWithContext,
  type NodeLogger,
  // Circuit breaker
  NodeCircuitBreaker,
  type CircuitBreakerStatus,
  type CircuitState,
  // Configuration types
  NodeConfigSchema,
  NodeRetryConfigSchema,
  CircuitBreakerConfigSchema,
  NodeExecutionContextSchema,
  DEFAULT_RETRY_CONFIG,
  DEFAULT_CIRCUIT_BREAKER_CONFIG,
  RETRY_PRESETS,
  generateTraceId,
  generateGraphExecutionId,
  createNodeExecutionContext,
  type NodeConfig,
  type NodeConfigInput,
  type NodeRetryConfig,
  type NodeRetryConfigInput,
  type CircuitBreakerConfig,
  type CircuitBreakerConfigInput,
  type NodeExecutionContext,
  type NodeExecutionContextInput,
  type OnRetryAttemptCallback,
  type OnTimeoutCallback,
  // Metrics (WRKF-1021)
  createNodeMetricsCollector,
  MetricsErrorCategorySchema,
  NodeMetricsCollector,
  NodeMetricsSchema,
  SerializedMetricsSchema,
  ThresholdConfigSchema,
  type MetricsErrorCategory,
  type NodeMetrics,
  type NodeMetricsCollectorConfig,
  type OnFailureRateThresholdCallback,
  type OnLatencyThresholdCallback,
  type SerializedMetrics,
  type ThresholdConfig,
} from './runner/index.js'

// Nodes module exports - domain-specific node implementations
export {
  // Reality Intake Nodes (FLOW-021, FLOW-022)
  loadBaselineRealityNode,
  createLoadBaselineNode,
  findBaselineFiles,
  parseMarkdownSections,
  extractListItems,
  parseBaselineFile,
  loadMostRecentBaseline,
  BaselineRealitySectionSchema,
  BaselineRealitySchema,
  LoadBaselineConfigSchema,
  LoadBaselineResultSchema,
  type BaselineReality,
  type BaselineRealitySection,
  type LoadBaselineConfig,
  type LoadBaselineResult,
  type GraphStateWithBaseline,
  retrieveContextNode,
  createRetrieveContextNode,
  createScopedRetrieveContextNode,
  determineRelevantPatterns,
  shouldExcludeFile,
  matchesIncludePattern,
  walkDirectory,
  loadFileContent,
  retrieveContextForScope,
  ScopePatternSchema,
  StoryScopeSchema,
  FileContextSchema,
  RetrievedContextSchema,
  RetrieveContextConfigSchema,
  RetrieveContextResultSchema,
  type ScopePattern,
  type StoryScope,
  type FileContext,
  type RetrievedContext,
  type RetrieveContextConfig,
  type RetrieveContextResult,
  type GraphStateWithContext,
  // Story Nodes (FLOW-023)
  storySeedNode,
  createStorySeedNode,
  createPrefilledStorySeedNode,
  generateStoryId,
  extractConstraintsFromBaseline,
  extractAffectedFiles,
  generateInitialACs,
  estimateComplexity,
  generateStorySeed,
  StoryRequestSchema,
  AcceptanceCriterionSchema,
  StoryStructureSchema,
  SeedConfigSchema,
  SeedResultSchema,
  type StoryRequest,
  type AcceptanceCriterion,
  type StoryStructure,
  type SeedConfig,
  type SeedResult,
  type GraphStateWithStorySeed,
} from './nodes/index.js'
