openapi: 3.0.3
info:
  title: LEGO Projects API
  version: 1.0.1
  description: |
    Comprehensive API for LEGO MOC Instructions application with enhanced security features.
    
    **Core Features:**
    - User profile management with avatar uploads
    - Gallery and album management with image optimization
    - MOC instructions and file management with download capabilities
    - Wishlist functionality with reordering and search
    - Full-text search via Elasticsearch
    - Image processing and optimization
    - File upload with virus scanning and content validation
    
    **Security Features:**
    - File content validation and virus scanning
    - Rate limiting and access control
    - Image processing and optimization
    - Authentication via JWT cookies
    - Request sanitization and security headers
    - File access control and ownership validation
    
    **File Upload:**
    - **Images**: JPEG, PNG, HEIC, and WebP formats (10MB max, 0-3 per MOC)
    - **Instructions**: PDF and .io formats (50MB max, 1+ required per MOC)
    - **Parts Lists**: CSV, XML, JSON, PDF, TXT formats (10MB max, 0-10 per MOC)
    - Automatic image optimization and resizing
    - Secure file storage with S3 or local fallback
    - Virus scanning and content validation
    - Environment-aware storage (local in dev, S3 in production)
    
    **Search & Indexing:**
    - Elasticsearch integration for full-text search
    - Real-time indexing of MOC instructions and wishlist items
    - Advanced filtering and sorting capabilities
    - Category-based filtering for wishlist items
    
    **Database:**
    - PostgreSQL with Drizzle ORM
    - Optimized indexes for lazy loading
    - Cascade deletes for data integrity
    - UUID primary keys for security
    
  contact:
    name: LEGO MOC Instructions Team
    email: support@lego-moc-instructions.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:3000
    description: Native development server (npm run dev)
  - url: https://api.lego-moc-instructions.com
    description: Production server

paths:
  # Health Check
  /:
    get:
      tags:
        - Health
      summary: Health check
      description: Check if the LEGO Projects API is running
      responses:
        '200':
          description: API is healthy
          content:
            text/plain:
              schema:
                type: string
                example: "Lego Projects API is running"
  
  # User Profile Management
  /api/users/{id}:
    $ref: './paths/users.yaml#/api/users/{id}'
  /api/users/{id}/avatar:
    $ref: './paths/users.yaml#/api/users/{id}/avatar'
  
  # Gallery Management
  /api/images:
    $ref: './paths/images.yaml#/api/images'
  /api/images/{id}:
    $ref: './paths/images.yaml#/api/images/{id}'
  /api/albums:
    $ref: './paths/albums.yaml#/api/albums'
  /api/albums/{id}:
    $ref: './paths/albums.yaml#/api/albums/{id}'
  /api/gallery:
    $ref: './paths/gallery.yaml#/api/gallery'
  /api/flag:
    $ref: './paths/flag.yaml#/api/flag'
  /api/csrf:
    $ref: './paths/csrf.yaml#/api/csrf'
  
  # MOC Instructions Management
  /api/mocs:
    $ref: './paths/moc-instructions.yaml#/api/mocs'
  /api/mocs/with-files:
    $ref: './paths/moc-instructions.yaml#/api/mocs/with-files'
  /api/mocs/test-auth:
    $ref: './paths/moc-instructions.yaml#/api/mocs/test-auth'
  /api/mocs/search:
    $ref: './paths/moc-instructions.yaml#/api/mocs/search'
  /api/mocs/{id}:
    $ref: './paths/moc-instructions.yaml#/api/mocs/{id}'
  /api/mocs/{id}/files:
    $ref: './paths/moc-instructions.yaml#/api/mocs/{id}/files'
  /api/mocs/{id}/files/{fileId}:
    $ref: './paths/moc-instructions.yaml#/api/mocs/{id}/files/{fileId}'
  /api/mocs/{id}/files/{fileId}/download-info:
    $ref: './paths/moc-instructions.yaml#/api/mocs/{id}/files/{fileId}/download-info'
  /api/mocs/{id}/files/{fileId}/download:
    $ref: './paths/moc-instructions.yaml#/api/mocs/{id}/files/{fileId}/download'
  /api/mocs/{id}/gallery-images:
    $ref: './paths/moc-instructions.yaml#/api/mocs/{id}/gallery-images'
  /api/mocs/{id}/gallery-images/{galleryImageId}:
    $ref: './paths/moc-instructions.yaml#/api/mocs/{id}/gallery-images/{galleryImageId}'
  
  # Wishlist Management
  /api/wishlist:
    $ref: './paths/wishlist.yaml#/api/wishlist'
  /api/wishlist/search:
    $ref: './paths/wishlist.yaml#/api/wishlist/search'
  /api/wishlist/{id}:
    $ref: './paths/wishlist.yaml#/api/wishlist/{id}'
  /api/wishlist/reorder:
    $ref: './paths/wishlist.yaml#/api/wishlist/reorder'
  /api/wishlist/reorder/debounced:
    $ref: './paths/wishlist.yaml#/api/wishlist/reorder/debounced'
  /api/wishlist/reorder/status:
    $ref: './paths/wishlist.yaml#/api/wishlist/reorder/status'
  /api/wishlist/reorder/cancel:
    $ref: './paths/wishlist.yaml#/api/wishlist/reorder/cancel'
  /api/wishlist/upload-image:
    $ref: './paths/wishlist.yaml#/api/wishlist/upload-image'
  /api/wishlist/image:
    $ref: './paths/wishlist.yaml#/api/wishlist/image'

tags:
  - name: Health
    description: Health check and monitoring
  - name: User Profiles
    description: User profile management and avatar uploads
  - name: Gallery
    description: Image gallery and album management
  - name: MOC Instructions
    description: MOC instructions and file management
  - name: Wishlist
    description: Wishlist management and reordering
  - name: Search
    description: Full-text search functionality
  - name: Files
    description: File upload, download, and management
  - name: Security
    description: Security and moderation features

components:
  schemas:
    $ref: './components/schemas.yaml'
  responses:
    $ref: './components/responses.yaml'
  parameters:
    $ref: './components/parameters.yaml'
  securitySchemes:
    $ref: './components/securitySchemes.yaml'

externalDocs:
  description: Find more info about the LEGO Projects API
  url: https://github.com/your-org/lego-moc-instructions/tree/main/apps/api/lego-projects-api

# Example Usage
x-examples:
  create-moc-with-files:
    summary: Create MOC with multiple instruction files
    description: |
      Example showing how to create a MOC instruction with multiple files using curl.

      **Step 1: Get test authentication token**
      ```bash
      curl -X POST http://localhost:9000/api/mocs/test-auth \
        -H "Content-Type: application/json"
      ```

      **Step 2: Create MOC with files**
      ```bash
      curl -X POST http://localhost:9000/api/mocs/with-files \
        -H "Authorization: Bearer YOUR_TOKEN_HERE" \
        -F "title=Medieval Castle MOC" \
        -F "description=A detailed medieval castle with working drawbridge" \
        -F "tags=[\"castle\", \"medieval\", \"architecture\"]" \
        -F "difficulty=advanced" \
        -F "instructionsFile=@castle-part1.pdf" \
        -F "instructionsFile=@castle-part2.pdf" \
        -F "instructionsFile=@castle-details.io" \
        -F "partsLists=@parts-list.csv" \
        -F "partsLists=@parts-inventory.json" \
        -F "images=@castle-front.jpg" \
        -F "images=@castle-side.jpg" \
        -F "images=@castle-interior.jpg"
      ```

      **Step 3: Search for MOCs**
      ```bash
      curl -X GET "http://localhost:9000/api/mocs/search?q=castle&tags=medieval&limit=10" \
        -H "Authorization: Bearer YOUR_TOKEN_HERE"
      ```

  file-requirements:
    summary: File upload requirements and limits
    description: |
      **Instructions Files (Required):**
      - Formats: PDF, .io
      - Size limit: 50MB per file
      - Quantity: 1-10 files
      - Examples: building-instructions.pdf, castle.io, part1.pdf, part2.pdf

      **Parts Lists (Optional):**
      - Formats: CSV, XML, JSON, PDF, TXT
      - Size limit: 10MB per file
      - Quantity: 0-10 files
      - Examples: parts-list.csv, inventory.json, bom.xml

      **Images (Optional):**
      - Formats: JPEG, PNG, WebP
      - Size limit: 10MB per file
      - Quantity: 0-3 files
      - Note: First image becomes the MOC thumbnail
      - Examples: front-view.jpg, side-view.png, detail.webp

      **Storage:**
      - Development: Local storage in `uploads/moc-files/{userId}/`
      - Production: AWS S3 bucket with CloudFront CDN

      **File Organization:**
      ```
      uploads/moc-files/{userId}/
      ├── instructions/
      │   ├── castle-part1-{uuid}.pdf
      │   └── castle-part2-{uuid}.pdf
      ├── parts-lists/
      │   └── parts-list-{uuid}.csv
      └── images/
          ├── castle-front-{uuid}.jpg (thumbnail)
          └── castle-side-{uuid}.jpg
      ```
