openapi: 3.0.3
info:
  title: Lego Projects Profile API
  version: 1.0.0
  description: |
    API for user profile management with enhanced security features.
    
    **Security Features:**
    - File content validation and virus scanning
    - Rate limiting and access control
    - Image processing and optimization
    - Authentication via JWT cookies
    
    **File Upload:**
    - Supports JPEG, PNG, and HEIC formats
    - Maximum file size: 20MB
    - Automatic image optimization and resizing
    - Secure file storage with S3 or local fallback
servers:
  - url: /api/users
paths:
  $ref: './paths/users.yaml'
  /api/images:
    $ref: './paths/images.yaml#/api/images'
  /api/images/{id}:
    $ref: './paths/images.yaml#/api/images/{id}'
  /api/albums/{id}:
    $ref: './paths/albums.yaml#/api/albums/{id}'
  /api/flag:
    $ref: './paths/flag.yaml#/api/flag'
  /api/mocs:
    $ref: './paths/moc-instructions.yaml#/api/mocs'
  /api/mocs/{id}:
    $ref: './paths/moc-instructions.yaml#/api/mocs/{id}'
  /api/mocs/{id}/files/{fileId}/download-info:
    $ref: './paths/moc-instructions.yaml#/api/mocs/{id}/files/{fileId}/download-info'
  /api/mocs/{id}/files/{fileId}/download:
    $ref: './paths/moc-instructions.yaml#/api/mocs/{id}/files/{fileId}/download'
  /api/moc-instructions/{mocId}/parts-lists:
    $ref: './paths/moc-parts-lists.yaml#/moc-instructions/{mocId}/parts-lists'
  /api/moc-instructions/{mocId}/parts-lists/{partsListId}:
    $ref: './paths/moc-parts-lists.yaml#/moc-instructions/{mocId}/parts-lists/{partsListId}'
  /api/moc-instructions/{mocId}/parts-lists/{partsListId}/status:
    $ref: './paths/moc-parts-lists.yaml#/moc-instructions/{mocId}/parts-lists/{partsListId}/status'
  /api/user/parts-lists/summary:
    $ref: './paths/moc-parts-lists.yaml#/user/parts-lists/summary'
  /api/wishlist:
    $ref: './paths/wishlist.yaml#/api/wishlist'
  /api/wishlist/search:
    $ref: './paths/wishlist.yaml#/api/wishlist/search'
  /api/wishlist/{id}:
    $ref: './paths/wishlist.yaml#/api/wishlist/{id}'
  /api/wishlist/reorder:
    $ref: './paths/wishlist.yaml#/api/wishlist/reorder'
  /api/wishlist/reorder/debounced:
    $ref: './paths/wishlist.yaml#/api/wishlist/reorder/debounced'
  /api/wishlist/reorder/status:
    $ref: './paths/wishlist.yaml#/api/wishlist/reorder/status'
  /api/wishlist/reorder/cancel:
    $ref: './paths/wishlist.yaml#/api/wishlist/reorder/cancel'
  /api/wishlist/upload-image:
    $ref: './paths/wishlist.yaml#/api/wishlist/upload-image'
  /api/wishlist/image:
    $ref: './paths/wishlist.yaml#/api/wishlist/image'
components:
  schemas:
    $ref: './components/schemas.yaml'
  responses:
    $ref: './components/responses.yaml'
  parameters:
    $ref: './components/parameters.yaml'
  securitySchemes:
    $ref: './components/securitySchemes.yaml' 