/**
 * API Docs Worker
 *
 * Documentation worker that scopes to API handler/route files, proposes
 * API documentation updates based on the merge event diff.
 *
 * AC-5, AC-6, AC-18: Uses createLLMNode (60s timeout, 5 retries) since this worker
 * calls an LLM to propose documentation content.
 *
 * APIP-1040: Documentation Graph (Post-Merge)
 */

import { z } from 'zod'
import { logger } from '@repo/logger'
import { createLLMNode } from '../../runner/node-factory.js'
import type { GraphState } from '../../state/index.js'
import type {
  DocWorkerResult,
  DocGraphState,
  ProposedFileChange,
  ApiDocsWorkerConfig,
} from '../../graphs/doc-graph.js'

// ============================================================================
// Schemas
// ============================================================================

/**
 * Configuration schema for the API Docs Worker.
 */
export const ApiDocsWorkerNodeConfigSchema = z.object({
  /** Whether this worker is enabled */
  enabled: z.boolean().default(true),
  /** Whether to run in dry-run mode */
  dryRun: z.boolean().default(false),
  /** Timeout in milliseconds (must be >= 60000 per AC-18) */
  timeoutMs: z.number().positive().default(120000),
  /** Model to use for LLM generation */
  model: z.string().default('gpt-4o-mini'),
  /** File patterns to scope API docs discovery */
  filePatterns: z.array(z.string()).default(['apps/api/', 'handlers/', 'routes/']),
})

export type ApiDocsWorkerNodeConfig = z.infer<typeof ApiDocsWorkerNodeConfigSchema>

// ============================================================================
// Worker Implementation
// ============================================================================

/**
 * Filters changed files to those relevant to API documentation.
 */
function filterApiFiles(changedFiles: string[], filePatterns: string[]): string[] {
  return changedFiles.filter(file => filePatterns.some(pattern => file.includes(pattern)))
}

/**
 * Generates API documentation update proposals based on changed files.
 * Does NOT write to filesystem — returns ProposedFileChange objects.
 *
 * AC-6: Reads state.mergeEvent.changedFiles, generates proposed file content
 * changes, returns DocWorkerResult with success:true/false (never throws).
 */
export async function generateApiDocsChanges(
  mergeEvent: DocGraphState['mergeEvent'],
  config: ApiDocsWorkerNodeConfig,
): Promise<DocWorkerResult> {
  const startTime = Date.now()
  const warnings: string[] = []
  const proposedChanges: ProposedFileChange[] = []

  if (!mergeEvent) {
    return {
      workerName: 'api-docs',
      success: false,
      filesUpdated: [],
      proposedChanges: [],
      durationMs: Date.now() - startTime,
      error: 'No merge event provided',
      warnings: [],
      model: config.model,
    }
  }

  try {
    // Phase 1: Scope relevant files to API handlers/routes
    const relevantFiles = filterApiFiles(mergeEvent.changedFiles, config.filePatterns)

    // ED-1: Empty changedFiles — success:true with empty proposedChanges + warning
    if (relevantFiles.length === 0) {
      warnings.push(
        `api-docs: no API-relevant files found in changedFiles for story ${mergeEvent.storyId}`,
      )
      return {
        workerName: 'api-docs',
        success: true,
        filesUpdated: [],
        proposedChanges: [],
        durationMs: Date.now() - startTime,
        error: null,
        warnings,
        model: config.model,
      }
    }

    // Propose API documentation update
    // In a real implementation, this would call an LLM with the diff summary
    // to generate documentation content. For now, we propose a structured update.
    const proposedDoc: ProposedFileChange = {
      filePath: 'docs/api/api-reference.md',
      operation: 'update',
      content: [
        `# API Reference`,
        ``,
        `<!-- Auto-generated by Documentation Graph for story ${mergeEvent.storyId} -->`,
        ``,
        `## Changed Endpoints`,
        ``,
        `The following API files were updated in this merge:`,
        relevantFiles.map(f => `- \`${f}\``).join('\n'),
        ``,
        `## Summary`,
        ``,
        mergeEvent.diffSummary,
      ].join('\n'),
      reason: `API documentation update for story ${mergeEvent.storyId}: ${relevantFiles.length} handler/route file(s) changed`,
      workerName: 'api-docs',
    }

    proposedChanges.push(proposedDoc)

    logger.info('api-docs-worker: proposed documentation update', {
      storyId: mergeEvent.storyId,
      relevantFilesCount: relevantFiles.length,
      proposedChangesCount: proposedChanges.length,
    })

    const durationMs = Date.now() - startTime
    return {
      workerName: 'api-docs',
      success: true,
      filesUpdated: proposedChanges.map(c => c.filePath),
      proposedChanges,
      durationMs,
      error: null,
      warnings,
      model: config.model,
    }
  } catch (error) {
    // EC-1: Worker error — success:false with error set, does NOT throw
    const errorMessage = error instanceof Error ? error.message : String(error)
    logger.warn('api-docs-worker: error generating documentation', {
      storyId: mergeEvent.storyId,
      error: errorMessage,
    })

    return {
      workerName: 'api-docs',
      success: false,
      filesUpdated: [],
      proposedChanges: [],
      durationMs: Date.now() - startTime,
      error: errorMessage,
      warnings,
      model: config.model,
    }
  }
}

// ============================================================================
// LangGraph Node Factory
// ============================================================================

/**
 * AC-18: API Docs Worker node using createLLMNode (60s timeout, 5 retries).
 * Default export for use in graph wiring.
 */
export const apiDocsWorkerNode = createLLMNode(
  'doc-worker-api-docs',
  async (state: GraphState): Promise<Partial<GraphState>> => {
    const docState = state as unknown as DocGraphState
    const config = ApiDocsWorkerNodeConfigSchema.parse({})
    const result = await generateApiDocsChanges(docState.mergeEvent, config)

    return {
      workerResults: [result],
      proposedFileChanges: result.proposedChanges,
    } as unknown as Partial<GraphState>
  },
)

/**
 * Factory for creating API Docs Worker node with custom configuration.
 *
 * @param config - Worker configuration
 * @returns Configured LangGraph node function
 */
export function createApiDocsWorkerNode(config: Partial<ApiDocsWorkerConfig> = {}) {
  const fullConfig = ApiDocsWorkerNodeConfigSchema.parse(config)

  return createLLMNode(
    'doc-worker-api-docs',
    async (state: GraphState): Promise<Partial<GraphState>> => {
      const docState = state as unknown as DocGraphState
      const result = await generateApiDocsChanges(docState.mergeEvent, fullConfig)

      return {
        workerResults: [result],
        proposedFileChanges: result.proposedChanges,
      } as unknown as Partial<GraphState>
    },
  )
}
