/**
 * Architecture Docs Worker
 *
 * Documentation worker that scopes to architecture/config files, proposes
 * architecture documentation updates based on the merge event diff.
 *
 * AC-5, AC-6, AC-18: Uses createLLMNode (60s timeout, 5 retries).
 *
 * APIP-1040: Documentation Graph (Post-Merge)
 */

import { z } from 'zod'
import { logger } from '@repo/logger'
import { createLLMNode } from '../../runner/node-factory.js'
import type { GraphState } from '../../state/index.js'
import type {
  DocWorkerResult,
  DocGraphState,
  ProposedFileChange,
  ArchitectureDocsWorkerConfig,
} from '../../graphs/doc-graph.js'

// ============================================================================
// Schemas
// ============================================================================

export const ArchitectureDocsWorkerNodeConfigSchema = z.object({
  enabled: z.boolean().default(true),
  dryRun: z.boolean().default(false),
  timeoutMs: z.number().positive().default(120000),
  model: z.string().default('gpt-4o-mini'),
  filePatterns: z.array(z.string()).default(['architecture/', 'config/', '.config.ts', 'infra/']),
})

export type ArchitectureDocsWorkerNodeConfig = z.infer<
  typeof ArchitectureDocsWorkerNodeConfigSchema
>

// ============================================================================
// Worker Implementation
// ============================================================================

function filterArchitectureFiles(changedFiles: string[], filePatterns: string[]): string[] {
  return changedFiles.filter(file => filePatterns.some(pattern => file.includes(pattern)))
}

/**
 * Generates architecture documentation update proposals.
 * AC-6: Does NOT write to filesystem — returns DocWorkerResult.
 */
export async function generateArchitectureDocsChanges(
  mergeEvent: DocGraphState['mergeEvent'],
  config: ArchitectureDocsWorkerNodeConfig,
): Promise<DocWorkerResult> {
  const startTime = Date.now()
  const warnings: string[] = []
  const proposedChanges: ProposedFileChange[] = []

  if (!mergeEvent) {
    return {
      workerName: 'architecture-docs',
      success: false,
      filesUpdated: [],
      proposedChanges: [],
      durationMs: Date.now() - startTime,
      error: 'No merge event provided',
      warnings: [],
      model: config.model,
    }
  }

  try {
    const relevantFiles = filterArchitectureFiles(mergeEvent.changedFiles, config.filePatterns)

    // ED-1: Empty changedFiles path
    if (relevantFiles.length === 0) {
      warnings.push(
        `architecture-docs: no architecture files found in changedFiles for story ${mergeEvent.storyId}`,
      )
      return {
        workerName: 'architecture-docs',
        success: true,
        filesUpdated: [],
        proposedChanges: [],
        durationMs: Date.now() - startTime,
        error: null,
        warnings,
        model: config.model,
      }
    }

    const proposedDoc: ProposedFileChange = {
      filePath: 'docs/architecture/decisions.md',
      operation: 'update',
      content: [
        `# Architecture Decisions`,
        ``,
        `<!-- Auto-generated by Documentation Graph for story ${mergeEvent.storyId} -->`,
        ``,
        `## Updated Architecture Files`,
        ``,
        `The following architecture/config files were updated in this merge:`,
        relevantFiles.map(f => `- \`${f}\``).join('\n'),
        ``,
        `## Summary`,
        ``,
        mergeEvent.diffSummary,
      ].join('\n'),
      reason: `Architecture documentation update for story ${mergeEvent.storyId}: ${relevantFiles.length} architecture/config file(s) changed`,
      workerName: 'architecture-docs',
    }

    proposedChanges.push(proposedDoc)

    logger.info('architecture-docs-worker: proposed documentation update', {
      storyId: mergeEvent.storyId,
      relevantFilesCount: relevantFiles.length,
      proposedChangesCount: proposedChanges.length,
    })

    const durationMs = Date.now() - startTime
    return {
      workerName: 'architecture-docs',
      success: true,
      filesUpdated: proposedChanges.map(c => c.filePath),
      proposedChanges,
      durationMs,
      error: null,
      warnings,
      model: config.model,
    }
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error)
    logger.warn('architecture-docs-worker: error generating documentation', {
      storyId: mergeEvent.storyId,
      error: errorMessage,
    })

    return {
      workerName: 'architecture-docs',
      success: false,
      filesUpdated: [],
      proposedChanges: [],
      durationMs: Date.now() - startTime,
      error: errorMessage,
      warnings,
      model: config.model,
    }
  }
}

// ============================================================================
// LangGraph Node Factory
// ============================================================================

export const architectureDocsWorkerNode = createLLMNode(
  'doc-worker-architecture-docs',
  async (state: GraphState): Promise<Partial<GraphState>> => {
    const docState = state as unknown as DocGraphState
    const config = ArchitectureDocsWorkerNodeConfigSchema.parse({})
    const result = await generateArchitectureDocsChanges(docState.mergeEvent, config)

    return {
      workerResults: [result],
      proposedFileChanges: result.proposedChanges,
    } as unknown as Partial<GraphState>
  },
)

export function createArchitectureDocsWorkerNode(
  config: Partial<ArchitectureDocsWorkerConfig> = {},
) {
  const fullConfig = ArchitectureDocsWorkerNodeConfigSchema.parse(config)

  return createLLMNode(
    'doc-worker-architecture-docs',
    async (state: GraphState): Promise<Partial<GraphState>> => {
      const docState = state as unknown as DocGraphState
      const result = await generateArchitectureDocsChanges(docState.mergeEvent, fullConfig)

      return {
        workerResults: [result],
        proposedFileChanges: result.proposedChanges,
      } as unknown as Partial<GraphState>
    },
  )
}
