/**
 * Component Docs Worker
 *
 * Documentation worker that scopes to React component/JSX files, proposes
 * JSDoc and component documentation updates based on the merge event diff.
 *
 * AC-5, AC-6, AC-18: Uses createLLMNode (60s timeout, 5 retries).
 *
 * APIP-1040: Documentation Graph (Post-Merge)
 */

import { z } from 'zod'
import { logger } from '@repo/logger'
import { createLLMNode } from '../../runner/node-factory.js'
import type { GraphState } from '../../state/index.js'
import type {
  DocWorkerResult,
  DocGraphState,
  ProposedFileChange,
  ComponentDocsWorkerConfig,
} from '../../graphs/doc-graph.js'

// ============================================================================
// Schemas
// ============================================================================

export const ComponentDocsWorkerNodeConfigSchema = z.object({
  enabled: z.boolean().default(true),
  dryRun: z.boolean().default(false),
  timeoutMs: z.number().positive().default(120000),
  model: z.string().default('gpt-4o-mini'),
  filePatterns: z.array(z.string()).default(['.tsx', '.jsx', 'components/']),
})

export type ComponentDocsWorkerNodeConfig = z.infer<typeof ComponentDocsWorkerNodeConfigSchema>

// ============================================================================
// Worker Implementation
// ============================================================================

function filterComponentFiles(changedFiles: string[], filePatterns: string[]): string[] {
  return changedFiles.filter(file =>
    filePatterns.some(pattern => file.includes(pattern)),
  )
}

/**
 * Generates component documentation update proposals.
 * AC-6: Does NOT write to filesystem — returns DocWorkerResult with success:true/false.
 */
export async function generateComponentDocsChanges(
  mergeEvent: DocGraphState['mergeEvent'],
  config: ComponentDocsWorkerNodeConfig,
): Promise<DocWorkerResult> {
  const startTime = Date.now()
  const warnings: string[] = []
  const proposedChanges: ProposedFileChange[] = []

  if (!mergeEvent) {
    return {
      workerName: 'component-docs',
      success: false,
      filesUpdated: [],
      proposedChanges: [],
      durationMs: Date.now() - startTime,
      error: 'No merge event provided',
      warnings: [],
      model: config.model,
    }
  }

  try {
    const relevantFiles = filterComponentFiles(mergeEvent.changedFiles, config.filePatterns)

    // ED-1: Empty changedFiles path
    if (relevantFiles.length === 0) {
      warnings.push(
        `component-docs: no component files found in changedFiles for story ${mergeEvent.storyId}`,
      )
      return {
        workerName: 'component-docs',
        success: true,
        filesUpdated: [],
        proposedChanges: [],
        durationMs: Date.now() - startTime,
        error: null,
        warnings,
        model: config.model,
      }
    }

    const proposedDoc: ProposedFileChange = {
      filePath: 'docs/components/component-index.md',
      operation: 'update',
      content: [
        `# Component Documentation Index`,
        ``,
        `<!-- Auto-generated by Documentation Graph for story ${mergeEvent.storyId} -->`,
        ``,
        `## Updated Components`,
        ``,
        `The following component files were updated in this merge:`,
        relevantFiles.map(f => `- \`${f}\``).join('\n'),
        ``,
        `## Summary`,
        ``,
        mergeEvent.diffSummary,
      ].join('\n'),
      reason: `Component documentation update for story ${mergeEvent.storyId}: ${relevantFiles.length} component file(s) changed`,
      workerName: 'component-docs',
    }

    proposedChanges.push(proposedDoc)

    logger.info('component-docs-worker: proposed documentation update', {
      storyId: mergeEvent.storyId,
      relevantFilesCount: relevantFiles.length,
      proposedChangesCount: proposedChanges.length,
    })

    const durationMs = Date.now() - startTime
    return {
      workerName: 'component-docs',
      success: true,
      filesUpdated: proposedChanges.map(c => c.filePath),
      proposedChanges,
      durationMs,
      error: null,
      warnings,
      model: config.model,
    }
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error)
    logger.warn('component-docs-worker: error generating documentation', {
      storyId: mergeEvent.storyId,
      error: errorMessage,
    })

    return {
      workerName: 'component-docs',
      success: false,
      filesUpdated: [],
      proposedChanges: [],
      durationMs: Date.now() - startTime,
      error: errorMessage,
      warnings,
      model: config.model,
    }
  }
}

// ============================================================================
// LangGraph Node Factory
// ============================================================================

export const componentDocsWorkerNode = createLLMNode(
  'doc-worker-component-docs',
  async (state: GraphState): Promise<Partial<GraphState>> => {
    const docState = state as unknown as DocGraphState
    const config = ComponentDocsWorkerNodeConfigSchema.parse({})
    const result = await generateComponentDocsChanges(docState.mergeEvent, config)

    return {
      workerResults: [result],
      proposedFileChanges: result.proposedChanges,
    } as unknown as Partial<GraphState>
  },
)

export function createComponentDocsWorkerNode(config: Partial<ComponentDocsWorkerConfig> = {}) {
  const fullConfig = ComponentDocsWorkerNodeConfigSchema.parse(config)

  return createLLMNode(
    'doc-worker-component-docs',
    async (state: GraphState): Promise<Partial<GraphState>> => {
      const docState = state as unknown as DocGraphState
      const result = await generateComponentDocsChanges(docState.mergeEvent, fullConfig)

      return {
        workerResults: [result],
        proposedFileChanges: result.proposedChanges,
      } as unknown as Partial<GraphState>
    },
  )
}
