/**
 * README Guides Worker
 *
 * Documentation worker that scopes to README and docs/ files, proposes
 * README and guide documentation updates based on the merge event diff.
 *
 * AC-5, AC-6, AC-18: Uses createLLMNode (60s timeout, 5 retries).
 *
 * APIP-1040: Documentation Graph (Post-Merge)
 */

import { z } from 'zod'
import { logger } from '@repo/logger'
import { createLLMNode } from '../../runner/node-factory.js'
import type { GraphState } from '../../state/index.js'
import type {
  DocWorkerResult,
  DocGraphState,
  ProposedFileChange,
  ReadmeGuidesWorkerConfig,
} from '../../graphs/doc-graph.js'

// ============================================================================
// Schemas
// ============================================================================

export const ReadmeGuidesWorkerNodeConfigSchema = z.object({
  enabled: z.boolean().default(true),
  dryRun: z.boolean().default(false),
  timeoutMs: z.number().positive().default(120000),
  model: z.string().default('gpt-4o-mini'),
  filePatterns: z.array(z.string()).default(['README', 'docs/', '.md']),
})

export type ReadmeGuidesWorkerNodeConfig = z.infer<typeof ReadmeGuidesWorkerNodeConfigSchema>

// ============================================================================
// Worker Implementation
// ============================================================================

function filterReadmeGuideFiles(changedFiles: string[], filePatterns: string[]): string[] {
  return changedFiles.filter(file =>
    filePatterns.some(pattern => file.includes(pattern)),
  )
}

/**
 * Generates README/guide documentation update proposals.
 * AC-6: Does NOT write to filesystem — returns DocWorkerResult.
 */
export async function generateReadmeGuidesChanges(
  mergeEvent: DocGraphState['mergeEvent'],
  config: ReadmeGuidesWorkerNodeConfig,
): Promise<DocWorkerResult> {
  const startTime = Date.now()
  const warnings: string[] = []
  const proposedChanges: ProposedFileChange[] = []

  if (!mergeEvent) {
    return {
      workerName: 'readme-guides',
      success: false,
      filesUpdated: [],
      proposedChanges: [],
      durationMs: Date.now() - startTime,
      error: 'No merge event provided',
      warnings: [],
      model: config.model,
    }
  }

  try {
    const relevantFiles = filterReadmeGuideFiles(mergeEvent.changedFiles, config.filePatterns)

    // ED-1: Empty changedFiles path
    if (relevantFiles.length === 0) {
      warnings.push(
        `readme-guides: no README/doc files found in changedFiles for story ${mergeEvent.storyId}`,
      )
      return {
        workerName: 'readme-guides',
        success: true,
        filesUpdated: [],
        proposedChanges: [],
        durationMs: Date.now() - startTime,
        error: null,
        warnings,
        model: config.model,
      }
    }

    const proposedDoc: ProposedFileChange = {
      filePath: 'docs/guides/update-log.md',
      operation: 'update',
      content: [
        `# Guide Update Log`,
        ``,
        `<!-- Auto-generated by Documentation Graph for story ${mergeEvent.storyId} -->`,
        ``,
        `## Updated README/Guide Files`,
        ``,
        `The following documentation files were updated in this merge:`,
        relevantFiles.map(f => `- \`${f}\``).join('\n'),
        ``,
        `## Summary`,
        ``,
        mergeEvent.diffSummary,
      ].join('\n'),
      reason: `README/guides documentation update for story ${mergeEvent.storyId}: ${relevantFiles.length} documentation file(s) changed`,
      workerName: 'readme-guides',
    }

    proposedChanges.push(proposedDoc)

    logger.info('readme-guides-worker: proposed documentation update', {
      storyId: mergeEvent.storyId,
      relevantFilesCount: relevantFiles.length,
      proposedChangesCount: proposedChanges.length,
    })

    const durationMs = Date.now() - startTime
    return {
      workerName: 'readme-guides',
      success: true,
      filesUpdated: proposedChanges.map(c => c.filePath),
      proposedChanges,
      durationMs,
      error: null,
      warnings,
      model: config.model,
    }
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error)
    logger.warn('readme-guides-worker: error generating documentation', {
      storyId: mergeEvent.storyId,
      error: errorMessage,
    })

    return {
      workerName: 'readme-guides',
      success: false,
      filesUpdated: [],
      proposedChanges: [],
      durationMs: Date.now() - startTime,
      error: errorMessage,
      warnings,
      model: config.model,
    }
  }
}

// ============================================================================
// LangGraph Node Factory
// ============================================================================

export const readmeGuidesWorkerNode = createLLMNode(
  'doc-worker-readme-guides',
  async (state: GraphState): Promise<Partial<GraphState>> => {
    const docState = state as unknown as DocGraphState
    const config = ReadmeGuidesWorkerNodeConfigSchema.parse({})
    const result = await generateReadmeGuidesChanges(docState.mergeEvent, config)

    return {
      workerResults: [result],
      proposedFileChanges: result.proposedChanges,
    } as unknown as Partial<GraphState>
  },
)

export function createReadmeGuidesWorkerNode(config: Partial<ReadmeGuidesWorkerConfig> = {}) {
  const fullConfig = ReadmeGuidesWorkerNodeConfigSchema.parse(config)

  return createLLMNode(
    'doc-worker-readme-guides',
    async (state: GraphState): Promise<Partial<GraphState>> => {
      const docState = state as unknown as DocGraphState
      const result = await generateReadmeGuidesChanges(docState.mergeEvent, fullConfig)

      return {
        workerResults: [result],
        proposedFileChanges: result.proposedChanges,
      } as unknown as Partial<GraphState>
    },
  )
}
