/**
 * Markdown report generator for impact analysis
 * WISH-20210
 */
import { ImpactResult, ImpactFinding, ImpactCategory } from '../__types__/index.js'

/**
 * Generate a Markdown report from impact analysis results
 */
export function generateMarkdownReport(result: ImpactResult): string {
  const sections: string[] = []

  // Header
  sections.push('# Database Schema Change Impact Analysis\n')
  sections.push(`**Generated:** ${new Date().toISOString()}\n`)

  // Change Summary
  sections.push('## Change Summary\n')
  sections.push(`**Operation:** \`${result.changeSummary.operation}\`\n`)
  sections.push(`**Target:** \`${result.changeSummary.target}\`\n`)
  sections.push(`**Description:** ${result.changeSummary.description}\n`)

  // Risk Assessment
  sections.push('## Risk Assessment\n')
  sections.push(`- **Breaking Change:** ${result.riskAssessment.breaking ? '⚠️ YES' : '✅ NO'}\n`)
  sections.push(
    `- **Backward Compatible:** ${result.riskAssessment.backwardCompatible ? '✅ YES' : '❌ NO'}\n`,
  )
  sections.push(
    `- **Rollback Safe:** ${result.riskAssessment.rollbackSafe ? '✅ YES' : '⚠️ NO'}\n`,
  )
  sections.push(
    `- **Deployment Order:** ${result.riskAssessment.deploymentOrder.map(step => `\`${step}\``).join(' → ')}\n`,
  )

  // Effort Estimate
  sections.push('## Effort Estimate\n')
  sections.push(`**${result.effortEstimate}** (based on ${getTotalFindings(result)} affected files)\n`)

  // Impact by Category
  sections.push('## Impact Analysis\n')

  const categories: ImpactCategory[] = [
    'backend-service',
    'repository',
    'zod-schema',
    'frontend-component',
    'api-hook',
    'db-schema',
    'test',
  ]

  for (const category of categories) {
    const findings = result.findingsByCategory[category]
    if (findings && findings.length > 0) {
      sections.push(`### ${getCategoryLabel(category)} (${findings.length} files)\n`)

      for (const finding of findings) {
        sections.push(`#### \`${finding.file}\`\n`)
        sections.push(`- **Confidence:** ${getConfidenceEmoji(finding.confidence)} ${finding.confidence}\n`)
        sections.push(`- **Impact:** ${finding.description}\n`)
        sections.push(`- **Action:** ${finding.recommendation}\n`)
      }
    }
  }

  // Recommendations
  sections.push('## Recommendations\n')
  for (const recommendation of result.recommendations) {
    sections.push(`- ${recommendation}\n`)
  }

  // Footer
  sections.push('\n---\n')
  sections.push('*Generated by Schema Change Impact Analysis Tool (WISH-20210)*\n')

  return sections.join('\n')
}

/**
 * Get total number of findings
 */
function getTotalFindings(result: ImpactResult): number {
  return Object.values(result.findingsByCategory).reduce(
    (sum, findings) => sum + findings.length,
    0,
  )
}

/**
 * Get human-readable category label
 */
function getCategoryLabel(category: ImpactCategory): string {
  const labels: Record<ImpactCategory, string> = {
    'backend-service': 'Backend Services',
    'repository': 'Repositories',
    'zod-schema': 'Zod Schemas',
    'frontend-component': 'Frontend Components',
    'api-hook': 'API Hooks',
    'db-schema': 'Database Schema',
    'test': 'Tests',
  }

  return labels[category]
}

/**
 * Get emoji for confidence level
 */
function getConfidenceEmoji(confidence: string): string {
  const emojis: Record<string, string> = {
    high: '🔴',
    medium: '🟡',
    low: '🟢',
  }

  return emojis[confidence] || '⚪'
}
