packages:
  - 'apps/*'
  - 'apps/api/*'
  - 'apps/web/*'
  - 'packages/api-core'
  - 'packages/shared/*'
  - 'packages/core/*'
  - 'packages/features/*'
  - 'packages/backend/*'
  - 'packages/tools/*'
  - 'packages/dev/*'
