# Infrastructure Stack: Database
# Deploys: Aurora PostgreSQL Serverless v2, Secrets Manager, DB Subnet Group
#
# This stack contains all RDS-related resources and IAM policies.
# Can be deployed independently after network and security stacks.
#
# Deploy:
#   pnpm serverless deploy --config stacks/infrastructure/database.yml --stage dev
#
# Dependencies: network, security
# Dependents: functions-*, monitoring

service: lego-database

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  deploymentMethod: direct
  tags:
    Project: lego-api
    Environment: ${self:provider.stage}
    ManagedBy: Serverless
    Stack: database

custom:
  shared: ${file(../shared-config.yml)}
  stage: ${self:provider.stage}
  stageConfig: ${self:custom.shared.stages.${self:custom.stage}, self:custom.shared.stages.dev}

  # Import from dependent stacks
  privateSubnet1Id: ${cf:lego-network-${self:custom.stage}.PrivateSubnet1Id}
  privateSubnet2Id: ${cf:lego-network-${self:custom.stage}.PrivateSubnet2Id}
  databaseSecurityGroupId: ${cf:lego-security-${self:custom.stage}.DatabaseSecurityGroupId}

resources:
  Description: LEGO API Database Infrastructure (Aurora PostgreSQL Serverless v2)

  Resources:
    # DB Subnet Group - places database in private subnets
    DBSubnetGroup:
      Type: AWS::RDS::DBSubnetGroup
      Properties:
        DBSubnetGroupName: lego-api-db-subnet-group-${self:custom.stage}
        DBSubnetGroupDescription: Subnet group for LEGO API Aurora PostgreSQL
        SubnetIds:
          - ${self:custom.privateSubnet1Id}
          - ${self:custom.privateSubnet2Id}
        Tags:
          - Key: Name
            Value: lego-api-db-subnet-group-${self:custom.stage}
          - Key: Project
            Value: lego-api
          - Key: Environment
            Value: ${self:custom.stage}

    # Secrets Manager Secret for database credentials
    DatabaseSecret:
      Type: AWS::SecretsManager::Secret
      Properties:
        Name: lego-api-db-credentials-${self:custom.stage}
        Description: Aurora PostgreSQL credentials for LEGO API
        GenerateSecretString:
          SecretStringTemplate: '{"username": "postgres"}'
          GenerateStringKey: password
          PasswordLength: 32
          ExcludeCharacters: '"@/\'
        Tags:
          - Key: Name
            Value: lego-api-db-credentials-${self:custom.stage}
          - Key: Project
            Value: lego-api
          - Key: Environment
            Value: ${self:custom.stage}

    # Aurora PostgreSQL Serverless v2 Cluster
    AuroraCluster:
      Type: AWS::RDS::DBCluster
      DependsOn:
        - DBSubnetGroup
      Properties:
        DBClusterIdentifier: lego-api-aurora-${self:custom.stage}
        Engine: ${self:custom.shared.database.engine}
        EngineVersion: ${self:custom.shared.database.engineVersion}
        EngineMode: provisioned
        Port: ${self:custom.shared.database.port}
        ServerlessV2ScalingConfiguration:
          MinCapacity: ${self:custom.shared.database.minCapacity}
          MaxCapacity: ${self:custom.shared.database.maxCapacity}
        MasterUsername: !Sub '{{resolve:secretsmanager:${DatabaseSecret}:SecretString:username}}'
        MasterUserPassword: !Sub '{{resolve:secretsmanager:${DatabaseSecret}:SecretString:password}}'
        DatabaseName: ${self:custom.shared.database.name}
        DBSubnetGroupName: !Ref DBSubnetGroup
        VpcSecurityGroupIds:
          - ${self:custom.databaseSecurityGroupId}
        StorageEncrypted: true
        BackupRetentionPeriod: ${self:custom.shared.database.backupRetention}
        DeletionProtection: false
        EnableHttpEndpoint: true
        Tags:
          - Key: Name
            Value: lego-api-aurora-${self:custom.stage}
          - Key: Project
            Value: lego-api
          - Key: Environment
            Value: ${self:custom.stage}

    # Aurora PostgreSQL Serverless v2 Instance
    AuroraInstance:
      Type: AWS::RDS::DBInstance
      Properties:
        DBInstanceIdentifier: lego-api-aurora-instance-${self:custom.stage}
        DBClusterIdentifier: !Ref AuroraCluster
        DBInstanceClass: db.serverless
        Engine: ${self:custom.shared.database.engine}
        PubliclyAccessible: false
        Tags:
          - Key: Name
            Value: lego-api-aurora-instance-${self:custom.stage}
          - Key: Project
            Value: lego-api
          - Key: Environment
            Value: ${self:custom.stage}

    # Attach secret to RDS cluster for rotation
    SecretTargetAttachment:
      Type: AWS::SecretsManager::SecretTargetAttachment
      Properties:
        SecretId: !Ref DatabaseSecret
        TargetId: !Ref AuroraCluster
        TargetType: AWS::RDS::DBCluster

    # ===========================================
    # IAM Policies for Database Access
    # ===========================================

    # IAM Policy for Lambda functions to access database
    # This can be attached to Lambda execution roles via policy ARN
    DatabaseAccessPolicy:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        ManagedPolicyName: lego-api-database-access-${self:custom.stage}
        Description: Policy for Lambda functions to access Aurora PostgreSQL
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            # Secrets Manager access for database credentials
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
              Resource: !Ref DatabaseSecret
            # RDS Data API access (if using Data API)
            - Effect: Allow
              Action:
                - rds-data:ExecuteStatement
                - rds-data:BatchExecuteStatement
                - rds-data:BeginTransaction
                - rds-data:CommitTransaction
                - rds-data:RollbackTransaction
              Resource: !Sub 'arn:aws:rds:${AWS::Region}:${AWS::AccountId}:cluster:${AuroraCluster}'
            # CloudWatch Logs for RDS (optional - for troubleshooting)
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/rds/*'

  Outputs:
    AuroraClusterEndpoint:
      Description: Aurora PostgreSQL Cluster Endpoint
      Value: !GetAtt AuroraCluster.Endpoint.Address
      Export:
        Name: lego-database-${self:custom.stage}-ClusterEndpoint

    AuroraClusterPort:
      Description: Aurora PostgreSQL Cluster Port
      Value: !GetAtt AuroraCluster.Endpoint.Port
      Export:
        Name: lego-database-${self:custom.stage}-ClusterPort

    AuroraClusterReadEndpoint:
      Description: Aurora PostgreSQL Cluster Read Endpoint
      Value: !GetAtt AuroraCluster.ReadEndpoint.Address
      Export:
        Name: lego-database-${self:custom.stage}-ClusterReadEndpoint

    AuroraClusterIdentifier:
      Description: Aurora PostgreSQL Cluster Identifier
      Value: !Ref AuroraCluster
      Export:
        Name: lego-database-${self:custom.stage}-ClusterIdentifier

    AuroraClusterArn:
      Description: Aurora PostgreSQL Cluster ARN
      Value: !Sub 'arn:aws:rds:${AWS::Region}:${AWS::AccountId}:cluster:${AuroraCluster}'
      Export:
        Name: lego-database-${self:custom.stage}-ClusterArn

    DatabaseSecretArn:
      Description: Database Credentials Secret ARN
      Value: !Ref DatabaseSecret
      Export:
        Name: lego-database-${self:custom.stage}-SecretArn

    DatabaseSecretName:
      Description: Database Credentials Secret Name
      Value: !Sub 'lego-api-db-credentials-${self:custom.stage}'
      Export:
        Name: lego-database-${self:custom.stage}-SecretName

    DatabaseName:
      Description: Database Name
      Value: ${self:custom.shared.database.name}
      Export:
        Name: lego-database-${self:custom.stage}-DatabaseName

    DatabaseAccessPolicyArn:
      Description: IAM Policy ARN for database access
      Value: !Ref DatabaseAccessPolicy
      Export:
        Name: lego-database-${self:custom.stage}-AccessPolicyArn

    DBSubnetGroupName:
      Description: DB Subnet Group Name
      Value: !Ref DBSubnetGroup
      Export:
        Name: lego-database-${self:custom.stage}-SubnetGroupName
