id:
  name: id
  in: path
  required: true
  schema:
    type: string
    format: uuid
  description: Resource ID (user, album, or image)

albumId:
  name: albumId
  in: path
  required: true
  schema:
    type: string
    format: uuid
  description: Album ID

imageId:
  name: imageId
  in: path
  required: true
  schema:
    type: string
    format: uuid
  description: Image ID

userId:
  name: userId
  in: path
  required: true
  schema:
    type: string
    format: uuid
  description: User ID

csrfToken:
  name: X-CSRF-Token
  in: header
  required: true
  schema:
    type: string
  description: >
    CSRF header token required for state-changing requests when using cookie-based authentication.
    Must match the 'XSRF-TOKEN' cookie value. Obtain via GET /api/csrf.
