/**
 * Database Exports
 *
 * Re-exports client, schema, and types for convenient imports.
 */

export { getDbClient, closeDbClient, testConnection } from './client.js'
export {
  vector,
  knowledgeEntries,
  embeddingCache,
  adrs,
  auditLog,
  codeStandards,
  cohesionRules,
  lessonsLearned,
  rules,
  worktrees,
  stories,
  tasks,
  workStateHistory,
  deferredWrites,
  taskAuditLog,
  storyAuditLog,
  storyKnowledgeLinks,
  storyDependencies,
  storyContent,
  storyStateHistory,
  storyTouches,
  storyOutcomes,
  plans,
  planDetails,
  planDependencies,
  planStoryLinks,
  planRevisionHistory,
  planExecutionLog,
  workState,
  workflowExecutions,
  workflowCheckpoints,
  workflowAuditLog,
  agents,
  agentInvocations,
  agentOutcomes,
  agentDecisions,
  hitlDecisions,
  contextSessions,
  contextPacks,
  contextCacheHits,
  mlModels,
  modelMetrics,
  modelPredictions,
  trainingData,
  storyArtifacts,
  artifactCheckpoints,
  artifactContexts,
  artifactReviews,
  artifactElaborations,
  artifactAnalyses,
  artifactScopes,
  artifactPlans,
  artifactEvidence,
  artifactVerifications,
  artifactFixSummaries,
  artifactProofs,
  artifactQaGates,
  artifactCompletionReports,
  artifactStorySeeds,
  artifactTestPlans,
  artifactDevFeasibility,
  artifactUiuxNotes,
  storyTokenUsage,
  changeTelemetry,
  modelExperiments,
  modelAssignments,
  type KnowledgeEntry,
  type NewKnowledgeEntry,
  type EmbeddingCacheEntry,
  type NewEmbeddingCacheEntry,
  type Story,
  type NewStory,
  type StoryOutcome,
  type NewStoryOutcome,
  type Plan,
  type NewPlan,
  type WorkState,
  type WorkStateHistory,
  type Task,
  type SelectContextSession,
  type InsertContextSession,
  type SelectContextPack,
  type StoryArtifact,
} from './schema.js'
