/**
 * Worktree path generation utilities.
 *
 * AC-3: Worktree paths follow <repo_root>/.worktrees/<storyId>-<timestamp>/ convention.
 * The timestamp suffix prevents stale worktree collisions on retry (ED-3).
 *
 * @module supervisor/concurrency/worktree-path
 */

import { join } from 'path'

/**
 * Generates a unique worktree path for a given story.
 *
 * Uses Date.now() as timestamp to prevent stale-path collisions (ED-3).
 * Example: /repo/.worktrees/APIP-1010-1740000000000/
 *
 * @param repoRoot - Absolute path to the git repository root
 * @param storyId - Story identifier (e.g. 'APIP-1010')
 * @returns Absolute path for the new worktree
 */
export function generateWorktreePath(repoRoot: string, storyId: string): string {
  const timestamp = Date.now()
  return join(repoRoot, '.worktrees', `${storyId}-${timestamp}`)
}

/**
 * Extracts the storyId from a worktree path generated by generateWorktreePath.
 * Returns null if the path does not match the expected pattern.
 *
 * @param worktreePath - Absolute worktree path
 * @returns Story ID or null
 */
export function extractStoryIdFromWorktreePath(worktreePath: string): string | null {
  const basename = worktreePath.split('/').at(-1) ?? ''
  // Pattern: <storyId>-<timestamp> where timestamp is a 13-digit number
  const match = basename.match(/^(.+)-\d{13}$/)
  return match ? match[1] : null
}
