/**
 * Lambda Layer ARN Helper
 *
 * This module provides layer ARNs for use in sst.config.ts.
 * ARNs are read from files generated by build-and-deploy-layers.sh
 * or can be provided via environment variables.
 *
 * Usage in sst.config.ts:
 * ```typescript
 * import { getLayerArns } from './layers/get-layer-arns'
 *
 * const layers = getLayerArns(stage)
 *
 * new sst.aws.Function("MyFunction", {
 *   handler: "...",
 *   layers: layers.minimal
 * })
 * ```
 */

import { readFileSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

export interface LayerArns {
  /** Minimal layer: zod, uuid, AWS SDK S3 */
  minimal: string[]
  /** Standard layer: database, cache, search, core infrastructure */
  standard: string[]
  /** Processing layer: sharp, csv-parser, xmldom */
  processing: string[]
  /** Minimal + Standard combined */
  minimalStandard: string[]
  /** Minimal + Standard + Processing combined */
  all: string[]
}

/**
 * Get Lambda Layer ARNs for a given stage
 *
 * Priority:
 * 1. Environment variables (MINIMAL_LAYER_ARN, STANDARD_LAYER_ARN, PROCESSING_LAYER_ARN)
 * 2. ARN files generated by build-and-deploy-layers.sh
 * 3. Fallback to empty arrays (will cause deployment to fail with helpful error)
 *
 * @param stage - The deployment stage (dev, staging, production)
 * @returns LayerArns object with arrays of ARN strings
 */
export function getLayerArns(stage: string): LayerArns {
  const minimalArn = getLayerArn('minimal-layer', stage)
  const standardArn = getLayerArn('standard-layer', stage)
  const processingArn = getLayerArn('processing-layer', stage)

  return {
    minimal: minimalArn ? [minimalArn] : [],
    standard: standardArn ? [standardArn] : [],
    processing: processingArn ? [processingArn] : [],
    minimalStandard: [minimalArn, standardArn].filter(Boolean) as string[],
    all: [minimalArn, standardArn, processingArn].filter(Boolean) as string[],
  }
}

/**
 * Get a single layer ARN from environment variable or file
 */
function getLayerArn(layerName: string, stage: string): string | null {
  // 1. Try environment variable
  const envVarName = `${layerName.toUpperCase().replace(/-/g, '_')}_ARN`
  const envArn = process.env[envVarName]
  if (envArn) {
    console.log(`Using ${layerName} ARN from environment: ${envArn}`)
    return envArn
  }

  // 2. Try ARN file
  const arnFilePath = join(__dirname, layerName, `layer-arn-${stage}.txt`)
  if (existsSync(arnFilePath)) {
    try {
      const arn = readFileSync(arnFilePath, 'utf-8').trim()
      console.log(`Using ${layerName} ARN from file: ${arn}`)
      return arn
    } catch (error) {
      console.warn(`Failed to read ${arnFilePath}:`, error)
    }
  }

  // 3. Fallback
  console.warn(
    `⚠️  No ARN found for ${layerName} (stage: ${stage}). ` +
      `Run ./layers/build-and-deploy-layers.sh ${stage} to deploy layers.`,
  )
  return null
}

/**
 * Validate that all required layers are available
 * Throws an error if any layer ARN is missing
 */
export function validateLayerArns(layers: LayerArns): void {
  const missing: string[] = []

  if (layers.minimal.length === 0) missing.push('minimal-layer')
  if (layers.standard.length === 0) missing.push('standard-layer')
  if (layers.processing.length === 0) missing.push('processing-layer')

  if (missing.length > 0) {
    throw new Error(
      `Missing Lambda Layer ARNs: ${missing.join(', ')}\n\n` +
        `Please run: ./layers/build-and-deploy-layers.sh [stage] [region]\n` +
        `Or set environment variables: MINIMAL_LAYER_ARN, STANDARD_LAYER_ARN, PROCESSING_LAYER_ARN`,
    )
  }
}

/**
 * Get layer ARNs without validation (for optional usage)
 * Returns empty arrays for missing layers instead of throwing
 */
export function getLayerArnsOptional(stage: string): LayerArns {
  try {
    return getLayerArns(stage)
  } catch {
    return {
      minimal: [],
      standard: [],
      processing: [],
      minimalStandard: [],
      all: [],
    }
  }
}
