version: '3.8'

services:
  # LEGO MOC Instructions App (Frontend)
  lego-app:
    build:
      context: ../apps/web/lego-moc-instructions-app
      dockerfile: Dockerfile
    container_name: lego-moc-instructions-app
    restart: unless-stopped
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}
      - VITE_AUTH_API_URL=${VITE_AUTH_API_URL:-http://localhost:5000}
    networks:
      - lego-app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  lego-app-network:
    driver: bridge 