AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon Managed Grafana Workspace for User Metrics Observability'

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: 'Deployment stage/environment'

  ProjectOwnerEmail:
    Type: String
    Default: 'engineering@example.com'
    Description: 'Email address of the project owner for admin access'

Resources:
  # IAM Role for Grafana Workspace Service
  GrafanaWorkspaceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'user-metrics-grafana-workspace-role-${Stage}'
      Description: 'Service role for Amazon Managed Grafana workspace to access data sources'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: grafana.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref GrafanaCloudWatchPolicy
        - !Ref GrafanaLogsPolicy
        - !Ref GrafanaOpenSearchPolicy
      Tags:
        - Key: Project
          Value: UserMetrics
        - Key: Environment
          Value: !Ref Stage
        - Key: ManagedBy
          Value: CloudFormation
        - Key: CostCenter
          Value: Observability
        - Key: Owner
          Value: !Ref ProjectOwnerEmail
        - Key: Component
          Value: IAM
        - Key: Function
          Value: AccessControl
        - Key: Purpose
          Value: GrafanaWorkspaceService

  # CloudWatch Access Policy for Grafana
  GrafanaCloudWatchPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub 'user-metrics-grafana-cloudwatch-policy-${Stage}'
      Description: 'Allows Grafana workspace to access CloudWatch metrics and alarms'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cloudwatch:DescribeAlarmsForMetric
              - cloudwatch:DescribeAlarmHistory
              - cloudwatch:DescribeAlarms
              - cloudwatch:ListMetrics
              - cloudwatch:GetMetricStatistics
              - cloudwatch:GetMetricData
              - cloudwatch:GetInsightRuleReport
              - cloudwatch:ListDashboards
              - cloudwatch:GetDashboard
            Resource: '*'

  # CloudWatch Logs Access Policy for Grafana
  GrafanaLogsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub 'user-metrics-grafana-logs-policy-${Stage}'
      Description: 'Allows Grafana workspace to access CloudWatch Logs Insights'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
              - logs:GetLogEvents
              - logs:StartQuery
              - logs:StopQuery
              - logs:GetQueryResults
              - logs:GetLogRecord
            Resource: '*'

  # OpenSearch Access Policy for Grafana (for future Story 2.4)
  GrafanaOpenSearchPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub 'user-metrics-grafana-opensearch-policy-${Stage}'
      Description: 'Allows Grafana workspace to access OpenSearch domain'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - es:ESHttpGet
              - es:ESHttpPost
              - es:ESHttpHead
            Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/lego-api-opensearch-${Stage}/*'

  # Amazon Managed Grafana Workspace
  GrafanaWorkspace:
    Type: AWS::Grafana::Workspace
    Properties:
      Name: !Sub 'user-metrics-grafana-${Stage}'
      Description: 'User Metrics Observability Dashboards and Analytics'
      AccountAccessType: 'CURRENT_ACCOUNT'
      AuthenticationProviders:
        - 'AWS_SSO'
      PermissionType: 'SERVICE_MANAGED'
      RoleArn: !GetAtt GrafanaWorkspaceRole.Arn
      DataSources:
        - 'CLOUDWATCH'
        - 'PROMETHEUS' # For future use
      NotificationDestinations:
        - 'SNS'
      OrganizationRoleName: 'UserMetrics'
      # Essential tier configuration (budget-conscious)
      # Note: Tier is not directly configurable in CloudFormation
      # Must be set via AWS Console or CLI after creation
      Tags:
        - Key: Project
          Value: UserMetrics
        - Key: Environment
          Value: !Ref Stage
        - Key: ManagedBy
          Value: CloudFormation
        - Key: CostCenter
          Value: Observability
        - Key: Owner
          Value: !Ref ProjectOwnerEmail
        - Key: Component
          Value: Grafana
        - Key: Function
          Value: Visualization
        - Key: ServiceType
          Value: ManagedGrafana
        - Key: Tier
          Value: Essential
        - Key: DataSources
          Value: 'CloudWatch,Logs,OpenSearch'
        - Key: BudgetAlert
          Value: '$9'
        - Key: CostOptimization
          Value: 'Optimized'

Outputs:
  WorkspaceId:
    Description: 'Amazon Managed Grafana Workspace ID'
    Value: !Ref GrafanaWorkspace
    Export:
      Name: !Sub '${AWS::StackName}-WorkspaceId'

  WorkspaceEndpoint:
    Description: 'Amazon Managed Grafana Workspace URL'
    Value: !GetAtt GrafanaWorkspace.Endpoint
    Export:
      Name: !Sub '${AWS::StackName}-WorkspaceEndpoint'

  WorkspaceRoleArn:
    Description: 'IAM Role ARN for Grafana Workspace Service'
    Value: !GetAtt GrafanaWorkspaceRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-WorkspaceRoleArn'

  WorkspaceName:
    Description: 'Grafana Workspace Name'
    Value: !Sub 'user-metrics-grafana-${Stage}'
    Export:
      Name: !Sub '${AWS::StackName}-WorkspaceName'
