service: wishlist-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  main:
    handler: handler.main
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    target: node18
    platform: node
    concurrency: 10
