/**
 * Story State Enum
 *
 * Single source of truth for story lifecycle states.
 * Matches the canonical 13-state model in migration 1001_canonical_story_states.sql.
 *
 * Forward flow:
 *   backlog → created → elab → ready → in_progress → needs_code_review
 *     → ready_for_qa → in_qa → completed
 *
 * Recovery/terminal: cancelled, blocked, failed_code_review, failed_qa
 */

import { z } from 'zod'

export const StoryStateSchema = z.enum([
  // Pre-development
  'backlog', // Known work, not yet started
  'created', // Story stub generated by PM
  'elab', // Story elaboration in progress
  'ready', // Elaborated and ready for dev

  // Development
  'in_progress', // Dev agent actively implementing
  'needs_code_review', // Implementation complete, awaiting code review

  // QA
  'ready_for_qa', // Code review passed, awaiting QA
  'in_qa', // QA verification in progress
  'completed', // QA passed — story done

  // Recovery
  'failed_code_review', // Code review failed, needs fixes
  'failed_qa', // QA failed, needs fixes

  // Operational
  'blocked', // Waiting on external dependency
  'cancelled', // No longer needed
])

export type StoryState = z.infer<typeof StoryStateSchema>

export const STORY_STATES = StoryStateSchema.options

export const TERMINAL_STATES: StoryState[] = ['completed', 'cancelled']
export const RECOVERY_STATES: StoryState[] = ['failed_code_review', 'failed_qa']
export const ACTIVE_STATES: StoryState[] = [
  'in_progress',
  'needs_code_review',
  'ready_for_qa',
  'in_qa',
]
export const WORKABLE_STATES: StoryState[] = ['ready']
export const PRE_DEV_STATES: StoryState[] = ['backlog', 'created', 'elab', 'ready']

export function isTerminalState(state: StoryState): boolean {
  return TERMINAL_STATES.includes(state)
}

export function isActiveState(state: StoryState): boolean {
  return ACTIVE_STATES.includes(state)
}

export function isWorkableState(state: StoryState): boolean {
  return WORKABLE_STATES.includes(state)
}

export function isRecoveryState(state: StoryState): boolean {
  return RECOVERY_STATES.includes(state)
}

/**
 * Returns the next state in the standard forward progression.
 * Returns null for terminal states or states with branching outcomes.
 */
export function getNextState(state: StoryState): StoryState | null {
  const progression: Partial<Record<StoryState, StoryState>> = {
    backlog: 'created',
    created: 'elab',
    elab: 'ready',
    ready: 'in_progress',
    in_progress: 'needs_code_review',
    needs_code_review: 'ready_for_qa',
    ready_for_qa: 'in_qa',
    in_qa: 'completed',
  }
  return progression[state] ?? null
}
