/**
 * Zod Schemas for Embedding Client
 *
 * All types are defined as Zod schemas (no TypeScript interfaces).
 * Types are inferred using z.infer<typeof Schema>.
 *
 * @see KNOW-002 for embedding client implementation
 */

import { z } from 'zod'

/**
 * Embedding Schema
 *
 * A 1536-dimensional vector for text-embedding-3-small model.
 * Each dimension is a floating-point number.
 */
export const EmbeddingSchema = z.array(z.number()).length(1536)
export type Embedding = z.infer<typeof EmbeddingSchema>

/**
 * Embedding Request Schema
 *
 * Validates input text for embedding generation.
 * - Must be a non-empty string
 * - Whitespace-only strings are invalid
 */
export const EmbeddingRequestSchema = z
  .string()
  .min(1, 'Text must not be empty')
  .transform(val => val.trim())
  .refine(val => val.length > 0, 'Text must not be whitespace-only')

export type EmbeddingRequest = z.infer<typeof EmbeddingRequestSchema>

/**
 * Batch Embedding Request Schema
 *
 * Validates array of texts for batch embedding generation.
 * - Must contain at least one text
 * - Each text must satisfy EmbeddingRequestSchema
 */
export const BatchEmbeddingRequestSchema = z
  .array(EmbeddingRequestSchema)
  .min(1, 'Batch must contain at least one text')

export type BatchEmbeddingRequest = z.infer<typeof BatchEmbeddingRequestSchema>

/**
 * Embedding Response Schema (from OpenAI API)
 *
 * Validates the structure of OpenAI embeddings API response.
 * Simplified version focusing on the embedding data we need.
 */
export const OpenAIEmbeddingResponseSchema = z.object({
  object: z.literal('list'),
  data: z.array(
    z.object({
      object: z.literal('embedding'),
      embedding: z.array(z.number()), // Will be validated as 1536-length after extraction
      index: z.number(),
    }),
  ),
  model: z.string(),
  usage: z.object({
    prompt_tokens: z.number(),
    total_tokens: z.number(),
  }),
})

export type OpenAIEmbeddingResponse = z.infer<typeof OpenAIEmbeddingResponseSchema>

/**
 * Cache Entry Schema
 *
 * Represents a cached embedding in the database.
 * Matches the database schema from apps/api/knowledge-base/src/db/schema.ts
 */
export const CacheEntrySchema = z.object({
  id: z.string().uuid(),
  contentHash: z.string().length(64), // SHA-256 hash is always 64 hex characters
  model: z.string(),
  embedding: EmbeddingSchema,
  createdAt: z.date(),
})

export type CacheEntry = z.infer<typeof CacheEntrySchema>

/**
 * New Cache Entry Schema (for inserts)
 *
 * Same as CacheEntry but without id and createdAt (auto-generated by database)
 */
export const NewCacheEntrySchema = z.object({
  contentHash: z.string().length(64),
  model: z.string(),
  embedding: EmbeddingSchema,
})

export type NewCacheEntry = z.infer<typeof NewCacheEntrySchema>

/**
 * Embedding Client Config Schema
 *
 * Configuration for the EmbeddingClient instance.
 * All fields have sensible defaults.
 */
export const EmbeddingClientConfigSchema = z.object({
  /** OpenAI API key (required) */
  apiKey: z.string().min(1, 'OpenAI API key is required'),

  /** Embedding model to use */
  model: z.string().default('text-embedding-3-small'),

  /** Request timeout in milliseconds */
  timeoutMs: z.number().int().positive().default(30000),

  /** Number of retry attempts for transient failures */
  retryCount: z.number().int().min(0).max(5).default(3),

  /** Maximum concurrent requests to OpenAI API */
  maxConcurrentRequests: z.number().int().positive().default(10),

  /** Enable/disable caching */
  cacheEnabled: z.boolean().default(true),
})

export type EmbeddingClientConfig = z.infer<typeof EmbeddingClientConfigSchema>

/**
 * Retry Error Types
 *
 * Classification of errors for retry logic decisions.
 */
export const RetryErrorTypeSchema = z.enum([
  'RATE_LIMIT', // 429 - Retry with backoff
  'SERVER_ERROR', // 500 - Retry with backoff
  'TIMEOUT', // Network timeout - Retry
  'AUTH_ERROR', // 401 - Don't retry (permanent)
  'BAD_REQUEST', // 400 - Don't retry (permanent)
  'FORBIDDEN', // 403 - Don't retry (permanent)
  'UNKNOWN', // Other error - Don't retry
])

export type RetryErrorType = z.infer<typeof RetryErrorTypeSchema>

/**
 * Cache Statistics Schema
 *
 * For logging cache performance metrics.
 */
export const CacheStatsSchema = z.object({
  totalRequests: z.number().int().nonnegative(),
  cacheHits: z.number().int().nonnegative(),
  cacheMisses: z.number().int().nonnegative(),
  cacheHitRate: z.number().min(0).max(1), // Percentage as decimal (0.0 to 1.0)
  apiCallCount: z.number().int().nonnegative(),
  estimatedCostSaved: z.number().nonnegative(), // In dollars
})

export type CacheStats = z.infer<typeof CacheStatsSchema>
