import { resolve } from 'path'
import { defineConfig } from 'vite'
import dts from 'vite-plugin-dts'

export default defineConfig({
  plugins: [
    dts({
      insertTypesEntry: true,
      exclude: ['**/*.test.ts', '**/*.spec.ts'],
    }),
  ],
  build: {
    lib: {
      entry: {
        index: resolve(__dirname, 'src/index.ts'),
        'client/serverless-client': resolve(__dirname, 'src/client/serverless-client.ts'),
        'rtk/base-query': resolve(__dirname, 'src/rtk/base-query.ts'),
        'rtk/gallery-api': resolve(__dirname, 'src/rtk/gallery-api.ts'),
        'rtk/wishlist-api': resolve(__dirname, 'src/rtk/wishlist-api.ts'),
        'rtk/wishlist-gallery-api': resolve(__dirname, 'src/rtk/wishlist-gallery-api.ts'),
        'rtk/sets-api': resolve(__dirname, 'src/rtk/sets-api.ts'),
        'rtk/minifigs-api': resolve(__dirname, 'src/rtk/minifigs-api.ts'),
        'rtk/dashboard-api': resolve(__dirname, 'src/rtk/dashboard-api.ts'),
        'rtk/instructions-api': resolve(__dirname, 'src/rtk/instructions-api.ts'),
        'rtk/permissions-api': resolve(__dirname, 'src/rtk/permissions-api.ts'),
        'rtk/admin-api': resolve(__dirname, 'src/rtk/admin-api.ts'),
        'rtk/inspiration-api': resolve(__dirname, 'src/rtk/inspiration-api.ts'),
        'rtk/user-profile-api': resolve(__dirname, 'src/rtk/user-profile-api.ts'),
        'rtk/scraper-api': resolve(__dirname, 'src/rtk/scraper-api.ts'),
        'rtk/uploads-api': resolve(__dirname, 'src/rtk/uploads-api.ts'),
        'rtk/procurement-api': resolve(__dirname, 'src/rtk/procurement-api.ts'),
        'rtk/recommender-api': resolve(__dirname, 'src/rtk/recommender-api.ts'),
        'schemas/wishlist': resolve(__dirname, 'src/schemas/wishlist.ts'),
        'schemas/instructions/index': resolve(__dirname, 'src/schemas/instructions/index.ts'),
        'schemas/instructions/form': resolve(__dirname, 'src/schemas/instructions/form.ts'),
        'schemas/instructions/api': resolve(__dirname, 'src/schemas/instructions/api.ts'),
        'schemas/instructions/utils': resolve(__dirname, 'src/schemas/instructions/utils.ts'),
        'schemas/sets': resolve(__dirname, 'src/schemas/sets.ts'),
        'schemas/minifigs': resolve(__dirname, 'src/schemas/minifigs.ts'),
        'schemas/feature-flags': resolve(__dirname, 'src/schemas/feature-flags.ts'),
        'schemas/scraper': resolve(__dirname, 'src/schemas/scraper.ts'),
        'schemas/inspiration': resolve(__dirname, 'src/schemas/inspiration.ts'),
        'schemas/admin': resolve(__dirname, 'src/schemas/admin.ts'),
        'schemas/permissions': resolve(__dirname, 'src/schemas/permissions.ts'),
        'schemas/uploads': resolve(__dirname, 'src/schemas/uploads.ts'),
        'schemas/procurement': resolve(__dirname, 'src/schemas/procurement.ts'),
        'auth/cognito-integration': resolve(__dirname, 'src/auth/cognito-integration.ts'),
        'auth/auth-middleware': resolve(__dirname, 'src/auth/auth-middleware.ts'),
        'auth/rtk-auth-integration': resolve(__dirname, 'src/auth/rtk-auth-integration.ts'),
        'retry/retry-logic': resolve(__dirname, 'src/retry/retry-logic.ts'),
        'config/environments': resolve(__dirname, 'src/config/environments.ts'),
        'config/endpoints': resolve(__dirname, 'src/config/endpoints.ts'),
        'types/api-responses': resolve(__dirname, 'src/types/api-responses.ts'),
        'utils/authorization-errors': resolve(__dirname, 'src/utils/authorization-errors.ts'),
        'errors/error-mapping': resolve(__dirname, 'src/errors/error-mapping.ts'),
        'errors/auth-failure': resolve(__dirname, 'src/errors/auth-failure.ts'),
      },
      name: 'ApiClient',
      formats: ['es'],
    },
    rollupOptions: {
      external: [
        'react',
        'react-dom',
        '@reduxjs/toolkit',
        '@reduxjs/toolkit/query/react',
        'zod',
        /^@repo\/.*/,
      ],
      output: {
        entryFileNames: '[name].js',
        chunkFileNames: '[name].js',
      },
    },
    sourcemap: true,
  },
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.ts'],
  },
})
