/**
 * Knowledge Base Seed Script
 *
 * Seeds the KB-specific tables: knowledge_entries, tasks, stories, work_state.
 *
 * Idempotent at the TABLE level — if a table already contains any rows it is
 * skipped entirely. This prevents accidental double-seeding on an existing DB.
 *
 * Usage: pnpm kb:seed
 */

import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { config } from 'dotenv'
import { drizzle } from 'drizzle-orm/node-postgres'
import { Pool } from 'pg'
import { knowledgeEntries, tasks, stories, workState } from '../db/schema.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
config({ path: resolve(__dirname, '../../.env') })

// ---------------------------------------------------------------------------
// Output helpers
// ---------------------------------------------------------------------------

const C = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  cyan: '\x1b[36m',
  gray: '\x1b[90m',
}

function log(msg: string, color: keyof typeof C = 'reset'): void {
  console.log(`${C[color]}${msg}${C.reset}`)
}

// ---------------------------------------------------------------------------
// Placeholder embedding
// ---------------------------------------------------------------------------

/**
 * Zero-vector placeholder. Real embeddings are generated by the embedding
 * client the first time each entry is queried.
 */
const ZERO_VEC: number[] = new Array(1536).fill(0)

// ---------------------------------------------------------------------------
// Seed data
// ---------------------------------------------------------------------------

const KNOWLEDGE_ENTRIES = [
  {
    content: [
      '# Story Workflow Overview',
      '',
      'The development workflow follows these phases:',
      '1. **Elaboration**: PM creates stories with acceptance criteria',
      '2. **Planning**: Architect creates implementation plan',
      '3. **Implementation**: Developers implement the story',
      '4. **Verification**: QA verifies against acceptance criteria',
      '5. **Completion**: Story is marked complete and merged',
      '',
      'Each phase has specific entry and exit criteria.',
    ].join('\n'),
    role: 'all',
    entryType: 'note',
    tags: ['workflow', 'process', 'overview'],
  },
  {
    content: [
      '# Creating a New Story',
      '',
      "Use the /pm-story command with the 'create' action:",
      '1. Provide a descriptive title and context',
      '2. Define clear acceptance criteria',
      '3. Specify dependencies (if any)',
      '4. Assign priority (P0-P3)',
      '',
      'Stories should be small enough to complete in 1-2 days.',
    ].join('\n'),
    role: 'pm',
    entryType: 'note',
    tags: ['story', 'creation', 'pm-workflow'],
  },
  {
    content: [
      '# Implementing Backend Code',
      '',
      'When implementing backend code:',
      '1. **Follow existing patterns** — Check apps/api/ for similar implementations',
      '2. **Use Drizzle ORM** — All database operations use Drizzle',
      '3. **Validate with Zod** — All inputs must be validated with Zod schemas',
      '4. **Write tests** — Use Vitest for unit and integration tests',
      '5. **Handle errors** — Return meaningful error messages',
      '',
      'Always run `pnpm check-types` after changes.',
    ].join('\n'),
    role: 'dev',
    entryType: 'runbook',
    tags: ['backend', 'implementation', 'best-practice'],
  },
  {
    content: [
      '# Testing Requirements',
      '',
      'All code changes must include tests:',
      '1. **Unit tests** — Test individual functions in isolation',
      '2. **Integration tests** — Test database operations',
      '3. **E2E tests** — Test user flows (for frontend changes)',
      '',
      'Minimum coverage: 45% global',
      '',
      'Commands:',
      '- `pnpm test`          — Run tests for changed files',
      '- `pnpm test:coverage` — Run with coverage report',
      '- `pnpm test:all`      — Run everything',
      '',
      'Use semantic queries in React tests: getByRole, getByLabelText.',
    ].join('\n'),
    role: 'qa',
    entryType: 'runbook',
    tags: ['testing', 'coverage', 'quality'],
  },
  {
    content: [
      '# TypeScript + Zod Convention',
      '',
      'ALWAYS use Zod schemas for types — never use TypeScript interfaces.',
      '',
      '```typescript',
      "import { z } from 'zod'",
      '',
      'const UserSchema = z.object({',
      '  id: z.string().uuid(),',
      '  email: z.string().email(),',
      '})',
      'type User = z.infer<typeof UserSchema>',
      '```',
      '',
      'Benefits: runtime validation, automatic type inference, self-documenting constraints.',
    ].join('\n'),
    role: 'dev',
    entryType: 'constraint',
    tags: ['typescript', 'zod', 'types', 'convention'],
  },
  {
    content: [
      '# Logging Convention',
      '',
      'Never use console.log in production code. Always use the logger:',
      '',
      '```typescript',
      "import { logger } from '@repo/logger'",
      '',
      "logger.info('Operation completed', { userId, action })",
      "logger.warn('Deprecated feature used', { feature })",
      "logger.error('Operation failed', { error, context })",
      "logger.debug('Debug info', { data })",
      '```',
      '',
      'Structured JSON in production, pretty-printed in development.',
    ].join('\n'),
    role: 'dev',
    entryType: 'runbook',
    tags: ['logging', 'best-practice', 'debugging'],
  },
  {
    content: [
      '# No Barrel Files',
      '',
      'Do not create barrel files (index.ts re-exports).',
      '',
      '```typescript',
      '// CORRECT',
      "import { UserProfile } from './UserProfile/index'",
      '',
      '// WRONG',
      "import { UserProfile } from './components'",
      '```',
      '',
      'Barrel files cause circular dependencies and degrade IDE performance.',
    ].join('\n'),
    role: 'dev',
    entryType: 'constraint',
    tags: ['imports', 'barrel-files', 'convention'],
  },
  {
    content: [
      '# QA Gate Workflow',
      '',
      'A QA gate is required before any story can be marked complete:',
      '1. Run /qa-gate to trigger specialist sub-agents',
      '2. Gate produces a YAML file with PASS / CONCERNS / FAIL / WAIVED',
      '3. CONCERNS require acknowledgement before proceeding',
      '4. FAIL blocks completion until resolved',
      '',
      'Gate checks: requirements traceability, code quality, security,',
      'test coverage, accessibility.',
    ].join('\n'),
    role: 'qa',
    entryType: 'runbook',
    tags: ['qa-gate', 'workflow', 'quality'],
  },
  {
    content: [
      '# Drizzle ORM Decision',
      '',
      'Decision: Use Drizzle ORM for all database operations.',
      '',
      'Rationale:',
      '- Type-safe queries with TypeScript inference',
      '- Lightweight — no heavy runtime, no code generation',
      '- SQL-first: queries look like SQL, no surprises',
      '- Excellent migration tooling via drizzle-kit',
      '',
      'Guidelines:',
      '- Define all tables in src/db/schema.ts',
      '- Never write raw SQL unless pgvector-specific (IVFFlat index)',
      '- Use $inferSelect / $inferInsert for row types',
    ].join('\n'),
    role: 'dev',
    entryType: 'decision',
    tags: ['drizzle', 'database', 'orm', 'architecture'],
  },
  {
    content: [
      '# Monorepo Package Structure',
      '',
      'Key shared packages:',
      '- `@repo/app-component-library` — UI primitives and app-level components',
      '- `@repo/logger`               — Structured logging utility',
      '- `@repo/design-system`        — Design tokens',
      '- `@repo/accessibility`        — A11y utilities',
      '',
      'Workspace dependencies use `workspace:*`.',
      'Never edit package.json manually — always use pnpm commands.',
    ].join('\n'),
    role: 'all',
    entryType: 'note',
    tags: ['monorepo', 'packages', 'structure'],
  },
]

const TASKS = [
  {
    title: 'Document IVFFlat index tuning guidance',
    description:
      'The lists=100 parameter was chosen for initial scale. Document guidance for tuning as knowledge_entries grows beyond 10k rows. Reference KNOW-007.',
    taskType: 'improvement',
    priority: 'p2',
    status: 'open',
    tags: ['documentation', 'performance', 'pgvector'],
    estimatedEffort: 's',
  },
  {
    title: 'Implement embedding regeneration script',
    description:
      'Create a script to re-generate embeddings for all knowledge_entries when the embedding model changes. See docs/EMBEDDING-REGENERATION.md for specification.',
    taskType: 'feature_idea',
    priority: 'p1',
    status: 'triaged',
    tags: ['embeddings', 'migration', 'tooling'],
    estimatedEffort: 'm',
  },
  {
    title: 'Add per-session rate limiting to MCP tool handlers',
    description:
      'MCP tool handlers have no per-session rate limiting. Runaway agents can exhaust the database connection pool. Add limits before production rollout.',
    taskType: 'tech_debt',
    priority: 'p1',
    status: 'open',
    tags: ['rate-limiting', 'mcp', 'reliability'],
    estimatedEffort: 'm',
  },
  {
    title: 'Write integration tests for hybrid search',
    description:
      'The hybrid search path (semantic + keyword RRF fusion) lacks integration tests. Cover: empty results, single-match fallback, min_confidence filtering, explain mode.',
    taskType: 'follow_up',
    priority: 'p1',
    status: 'open',
    tags: ['testing', 'search', 'integration'],
    estimatedEffort: 'm',
  },
  {
    title: 'Profile IVFFlat query performance at scale',
    description:
      'Profile vector search with pgbench when knowledge_entries exceeds 10k rows. Tune lists parameter and consider HNSW index if IVFFlat degrades.',
    taskType: 'improvement',
    priority: 'p3',
    status: 'open',
    tags: ['performance', 'pgvector', 'index'],
    estimatedEffort: 'l',
  },
]

const STORIES = [
  {
    storyId: 'SEED-0001',
    feature: 'seed',
    title: 'Initial knowledge base seed data',
    priority: 'P4' as const,
    state: 'completed' as const,
  },
  {
    storyId: 'SEED-0002',
    feature: 'seed',
    title: 'Embedding cache warm-up for common queries',
    priority: 'P3' as const,
    state: 'backlog' as const,
  },
  {
    storyId: 'SEED-0003',
    feature: 'seed',
    title: 'Knowledge entry verification workflow',
    priority: 'P2' as const,
    state: 'ready' as const,
  },
]

const WORK_STATES = [
  {
    storyId: 'SEED-0002',
    branch: 'feat/seed-0002-embedding-cache-warmup',
    phase: 'planning',
    constraints: ['Must not exceed 1000 cache entries on warm-up', 'Must complete within 60s'],
    recentActions: ['Created story', 'Added to backlog'],
    nextSteps: ['Elaborate acceptance criteria', 'Draft implementation plan'],
    blockers: [],
    kbReferences: {},
  },
  {
    storyId: 'SEED-0003',
    branch: 'feat/seed-0003-verification-workflow',
    phase: 'ready-to-work',
    constraints: [
      'Verification must be idempotent',
      'Only the qa role may mark entries as verified',
    ],
    recentActions: ['Elaborated story', 'Approved for development'],
    nextSteps: ['Begin implementation', 'Write unit tests for verify endpoint'],
    blockers: [],
    kbReferences: {},
  },
]

// ---------------------------------------------------------------------------
// Seed functions — each skips if the table already has any rows
// ---------------------------------------------------------------------------

type Db = ReturnType<typeof drizzle>

async function seedKnowledgeEntries(db: Db): Promise<void> {
  const existing = await db.select({ id: knowledgeEntries.id }).from(knowledgeEntries).limit(1)
  if (existing.length > 0) {
    log('  knowledge_entries — table has data, skipping', 'yellow')
    return
  }

  const rows = KNOWLEDGE_ENTRIES.map(e => ({ ...e, embedding: ZERO_VEC }))
  await db.insert(knowledgeEntries).values(rows)
  log(`  knowledge_entries — inserted ${rows.length} rows`, 'green')
}

async function seedTasks(db: Db): Promise<void> {
  const existing = await db.select({ id: tasks.id }).from(tasks).limit(1)
  if (existing.length > 0) {
    log('  tasks — table has data, skipping', 'yellow')
    return
  }

  await db.insert(tasks).values(TASKS)
  log(`  tasks — inserted ${TASKS.length} rows`, 'green')
}

async function seedStories(db: Db): Promise<void> {
  const existing = await db.select({ storyId: stories.storyId }).from(stories).limit(1)
  if (existing.length > 0) {
    log('  stories — table has data, skipping', 'yellow')
    return
  }

  // stories.story_id is UNIQUE — onConflictDoNothing guards any retry edge cases
  await db.insert(stories).values(STORIES).onConflictDoNothing()
  log(`  stories — inserted ${STORIES.length} rows`, 'green')
}

async function seedWorkState(db: Db): Promise<void> {
  const existing = await db.select({ id: workState.id }).from(workState).limit(1)
  if (existing.length > 0) {
    log('  work_state — table has data, skipping', 'yellow')
    return
  }

  // work_state.story_id is UNIQUE — onConflictDoNothing guards any retry edge cases
  await db.insert(workState).values(WORK_STATES).onConflictDoNothing()
  log(`  work_state — inserted ${WORK_STATES.length} rows`, 'green')
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  log('\n════════════════════════════════════════', 'cyan')
  log('  Knowledge Base Seed', 'cyan')
  log('════════════════════════════════════════', 'cyan')
  log('  Tables with existing data are skipped.', 'gray')
  log('  Embeddings are zero-vectors; real vectors', 'gray')
  log('  are generated by the embedding client.', 'gray')
  log('════════════════════════════════════════\n', 'cyan')

  const password = process.env.KB_DB_PASSWORD
  if (!password) {
    log('[ERROR] KB_DB_PASSWORD is not set. Add it to .env.', 'red')
    process.exit(1)
  }

  const pool = new Pool({
    host: process.env.KB_DB_HOST || 'localhost',
    port: parseInt(process.env.KB_DB_PORT || '5433', 10),
    database: process.env.KB_DB_NAME || 'knowledgebase',
    user: process.env.KB_DB_USER || 'kbuser',
    password,
  })

  const db = drizzle(pool)

  try {
    await seedKnowledgeEntries(db)
    await seedTasks(db)
    await seedStories(db)
    await seedWorkState(db)

    log('\n  Done.', 'green')
  } catch (error) {
    log('\n[ERROR] Seed failed:', 'red')
    console.error(error)
    process.exit(1)
  } finally {
    await pool.end()
  }
}

main()
