# Serverless Framework Configuration for Cognito User Pool
# Standalone stack for authentication infrastructure
#
# Usage:
#   pnpm serverless deploy --config serverless-cognito.yml --stage dev
#   pnpm serverless deploy --config serverless-cognito.yml --stage staging
#   pnpm serverless deploy --config serverless-cognito.yml --stage production

service: lego-api-cognito

frameworkVersion: '3'

# Custom Variables
custom:
  stage: ${opt:stage, 'dev'}

  # ===========================================
  # Social Login OAuth Credentials (COMMENTED OUT - not yet configured)
  # ===========================================
  # Uncomment when ready to enable social login. Store secrets in GitHub:
  #   Settings > Secrets and variables > Actions
  #
  # Using GitHub CLI:
  #   gh secret set GOOGLE_CLIENT_ID --body "YOUR_CLIENT_ID"
  #   gh secret set GOOGLE_CLIENT_SECRET --body "YOUR_SECRET"
  #   gh secret set APPLE_CLIENT_ID --body "YOUR_CLIENT_ID"
  #   gh secret set APPLE_TEAM_ID --body "YOUR_TEAM_ID"
  #   gh secret set APPLE_KEY_ID --body "YOUR_KEY_ID"
  #   gh secret set APPLE_PRIVATE_KEY --body "YOUR_PRIVATE_KEY"
  #   gh secret set FACEBOOK_CLIENT_ID --body "YOUR_CLIENT_ID"
  #   gh secret set FACEBOOK_CLIENT_SECRET --body "YOUR_SECRET"
  #
  # In GitHub Actions workflow, expose as env vars:
  #   env:
  #     GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  #     GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  #     ...
  #
  # oauth:
  #   google:
  #     clientId: ${env:GOOGLE_CLIENT_ID, ''}
  #     clientSecret: ${env:GOOGLE_CLIENT_SECRET, ''}
  #   apple:
  #     clientId: ${env:APPLE_CLIENT_ID, ''}
  #     teamId: ${env:APPLE_TEAM_ID, ''}
  #     keyId: ${env:APPLE_KEY_ID, ''}
  #     privateKey: ${env:APPLE_PRIVATE_KEY, ''}
  #   facebook:
  #     clientId: ${env:FACEBOOK_CLIENT_ID, ''}
  #     clientSecret: ${env:FACEBOOK_CLIENT_SECRET, ''}

# Provider Configuration
provider:
  name: aws
  runtime: nodejs20.x
  stage: ${self:custom.stage}
  region: ${opt:region, 'us-east-1'}

  # AWS Tags (applied to all resources)
  tags:
    Project: lego-api
    Environment: ${self:custom.stage}
    ManagedBy: Serverless
    CostCenter: Engineering
    Owner: engineering@bricklink.com

# No functions in this stack - just CloudFormation resources
functions: {}

# CloudFormation Resources
resources:
  Description: LEGO API Cognito Authentication Stack

  # CloudFormation Conditions for social login providers (COMMENTED OUT)
  # Conditions:
  #   HasGoogleCredentials: !Not [!Equals ['${self:custom.oauth.google.clientId}', '']]
  #   HasAppleCredentials: !Not [!Equals ['${self:custom.oauth.apple.clientId}', '']]
  #   HasFacebookCredentials: !Not [!Equals ['${self:custom.oauth.facebook.clientId}', '']]

  Resources:
    # ===========================================
    # Cognito User Pool for Authentication
    # ===========================================

    # Cognito User Pool - email-based sign-in with OTP verification
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: lego-moc-users-${self:custom.stage}
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        # Require email verification before user can sign in
        UserAttributeUpdateSettings:
          AttributesRequireVerificationBeforeUpdate:
            - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireUppercase: true
            RequireNumbers: true
            RequireSymbols: false
            TemporaryPasswordValidityDays: 7
        # Use OTP code verification instead of link
        VerificationMessageTemplate:
          DefaultEmailOption: CONFIRM_WITH_CODE
          EmailMessage: 'Your LEGO MOC verification code is {####}. This code expires in 24 hours.'
          EmailSubject: 'LEGO MOC - Verify your email'
          EmailMessageByLink: 'Please click the link below to verify your email address. {##Verify Email##}'
          EmailSubjectByLink: 'LEGO MOC - Verify your email'
        Schema:
          - Name: email
            AttributeDataType: String
            Mutable: true
            Required: true
          - Name: avatar_url
            AttributeDataType: String
            Mutable: true
            Required: false
          - Name: preferences
            AttributeDataType: String
            Mutable: true
            Required: false
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
        DeletionProtection: INACTIVE
        UserPoolTags:
          Environment: ${self:custom.stage}
          Project: lego-api
          Service: Authentication

    # Cognito User Pool Client - OAuth 2.0 authorization code flow
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      DependsOn:
        - CognitoUserPool
      Properties:
        ClientName: lego-moc-web-client-${self:custom.stage}
        UserPoolId: !Ref CognitoUserPool
        AllowedOAuthFlows:
          - code
        AllowedOAuthScopes:
          - openid
          - email
          - profile
        AllowedOAuthFlowsUserPoolClient: true
        CallbackURLs:
          - http://localhost:3002/auth/callback
          - http://localhost:5173/auth/callback
          # Production callback URLs (add your domain here)
          # - https://app.legomoc.com/auth/callback
        LogoutURLs:
          - http://localhost:3002/auth/logout
          - http://localhost:5173/auth/logout
          # Production logout URLs (add your domain here)
          # - https://app.legomoc.com/auth/logout
        # Identity providers - COGNITO is always enabled
        SupportedIdentityProviders:
          - COGNITO
          # Social providers - uncomment after configuring SSM parameters
          # - Google
          # - SignInWithApple
          # - Facebook
        AccessTokenValidity: 60
        IdTokenValidity: 60
        RefreshTokenValidity: 43200
        TokenValidityUnits:
          AccessToken: minutes
          IdToken: minutes
          RefreshToken: minutes
        GenerateSecret: false
        PreventUserExistenceErrors: ENABLED
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH

    # Cognito User Pool Domain - for hosted UI (optional)
    CognitoUserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        Domain: !Sub 'lego-moc-${self:custom.stage}-${AWS::AccountId}'
        UserPoolId: !Ref CognitoUserPool

    # ===========================================
    # Social Identity Providers (COMMENTED OUT - not yet configured)
    # ===========================================
    # Uncomment when ready to enable social login (also uncomment oauth config above)
    #
    # # Google Identity Provider
    # # Setup: https://console.cloud.google.com/apis/credentials
    # # Required OAuth scopes: openid, email, profile
    # GoogleIdentityProvider:
    #   Type: AWS::Cognito::UserPoolIdentityProvider
    #   Condition: HasGoogleCredentials
    #   Properties:
    #     UserPoolId: !Ref CognitoUserPool
    #     ProviderName: Google
    #     ProviderType: Google
    #     ProviderDetails:
    #       client_id: ${self:custom.oauth.google.clientId}
    #       client_secret: ${self:custom.oauth.google.clientSecret}
    #       authorize_scopes: openid email profile
    #     AttributeMapping:
    #       email: email
    #       name: name
    #       picture: picture
    #       username: sub
    #
    # # Apple Identity Provider
    # # Setup: https://developer.apple.com/account/resources/identifiers/list/serviceId
    # # Required: Services ID, Team ID, Key ID, and Private Key
    # AppleIdentityProvider:
    #   Type: AWS::Cognito::UserPoolIdentityProvider
    #   Condition: HasAppleCredentials
    #   Properties:
    #     UserPoolId: !Ref CognitoUserPool
    #     ProviderName: SignInWithApple
    #     ProviderType: SignInWithApple
    #     ProviderDetails:
    #       client_id: ${self:custom.oauth.apple.clientId}
    #       team_id: ${self:custom.oauth.apple.teamId}
    #       key_id: ${self:custom.oauth.apple.keyId}
    #       private_key: ${self:custom.oauth.apple.privateKey}
    #       authorize_scopes: name email
    #     AttributeMapping:
    #       email: email
    #       name: name
    #       username: sub
    #
    # # Facebook Identity Provider
    # # Setup: https://developers.facebook.com/apps/
    # # Required permissions: email, public_profile
    # FacebookIdentityProvider:
    #   Type: AWS::Cognito::UserPoolIdentityProvider
    #   Condition: HasFacebookCredentials
    #   Properties:
    #     UserPoolId: !Ref CognitoUserPool
    #     ProviderName: Facebook
    #     ProviderType: Facebook
    #     ProviderDetails:
    #       client_id: ${self:custom.oauth.facebook.clientId}
    #       client_secret: ${self:custom.oauth.facebook.clientSecret}
    #       authorize_scopes: email public_profile
    #     AttributeMapping:
    #       email: email
    #       name: name
    #       picture: picture
    #       username: id

  Outputs:
    CognitoUserPoolId:
      Description: Cognito User Pool ID
      Value: !Ref CognitoUserPool
      Export:
        Name: lego-api-${self:custom.stage}-CognitoUserPoolId

    CognitoUserPoolArn:
      Description: Cognito User Pool ARN
      Value: !GetAtt CognitoUserPool.Arn
      Export:
        Name: lego-api-${self:custom.stage}-CognitoUserPoolArn

    CognitoUserPoolClientId:
      Description: Cognito User Pool Client ID
      Value: !Ref CognitoUserPoolClient
      Export:
        Name: lego-api-${self:custom.stage}-CognitoUserPoolClientId

    CognitoUserPoolDomain:
      Description: Cognito User Pool Domain
      Value: !Sub 'https://lego-moc-${self:custom.stage}-${AWS::AccountId}.auth.${self:provider.region}.amazoncognito.com'
      Export:
        Name: lego-api-${self:custom.stage}-CognitoUserPoolDomain

    CognitoIssuerUrl:
      Description: Cognito Issuer URL (for JWT validation)
      Value: !Sub 'https://cognito-idp.${self:provider.region}.amazonaws.com/${CognitoUserPool}'
      Export:
        Name: lego-api-${self:custom.stage}-CognitoIssuerUrl
