version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    command: pnpm run dev
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data: 