#!/bin/bash
#
# Automated Fix Script for lego-api-serverless TypeScript Errors
# Generated by dev agent (James)
# Date: 2025-11-23
#
# Usage: ./apply-fixes.sh
#

set -e

cd "$(dirname "$0")"

echo "🔧 Starting systematic TypeScript error fixes..."
echo ""

# =============================================================================
# PHASE 2: Database Schema (find and replace manually needed)
# =============================================================================
echo "📋 PHASE 2: Database Schema References"
echo "--------------------------------------"
echo "⚠️  MANUAL ACTION REQUIRED:"
echo ""
echo "1. Find schema file location:"
echo "   find . -name '*schema*.ts' -path '*/database/*' -o -path '*/db/*' | grep -v node_modules | grep -v '.sst'"
echo ""
echo "2. Check table names:"
echo "   grep -n 'mocParts' [schema-file-path]"
echo ""
echo "3. Then run these replacements:"
echo "   # If schema has 'mocPartsLists':"
echo "   find endpoints/moc-parts-lists -name '*.ts' -exec sed -i '' 's/mocPartsListItems/mocPartsLists/g' {} +"
echo "   find endpoints/moc-parts-lists -name '*.ts' -exec sed -i '' 's/mocInstructionId/mocId/g' {} +"
echo ""
echo "Press ENTER to continue to Phase 3..."
read

# =============================================================================
# PHASE 3: Response Helpers - Add Error Codes
# =============================================================================
echo ""
echo "📋 PHASE 3: Response Helper Signatures"
echo "---------------------------------------"
echo "Updating errorResponse() calls to include error codes..."

# Create backup
cp -r endpoints/moc-parts-lists endpoints/moc-parts-lists.backup

# Update 400 errors (Validation)
find endpoints/moc-parts-lists -name '*.ts' -exec sed -i '' \
  "s/errorResponse(400, '\([^']*\)')/errorResponse(400, 'VALIDATION_ERROR', '\1')/g" {} +

find endpoints/moc-parts-lists -name '*.ts' -exec sed -i '' \
  's/errorResponse(400, "\([^"]*\)")/errorResponse(400, "VALIDATION_ERROR", "\1")/g' {} +

# Update 403 errors (Forbidden)
find endpoints/moc-parts-lists -name '*.ts' -exec sed -i '' \
  "s/errorResponse(403, '\([^']*\)')/errorResponse(403, 'FORBIDDEN', '\1')/g" {} +

find endpoints/moc-parts-lists -name '*.ts' -exec sed -i '' \
  's/errorResponse(403, "\([^"]*\)")/errorResponse(403, "FORBIDDEN", "\1")/g' {} +

# Update 404 errors (Not Found)
find endpoints/moc-parts-lists -name '*.ts' -exec sed -i '' \
  "s/errorResponse(404, '\([^']*\)')/errorResponse(404, 'NOT_FOUND', '\1')/g" {} +

find endpoints/moc-parts-lists -name '*.ts' -exec sed -i '' \
  's/errorResponse(404, "\([^"]*\)")/errorResponse(404, "NOT_FOUND", "\1")/g' {} +

# Update 409 errors (Conflict)
find endpoints/moc-parts-lists -name '*.ts' -exec sed -i '' \
  "s/errorResponse(409, '\([^']*\)')/errorResponse(409, 'CONFLICT', '\1')/g" {} +

find endpoints/moc-parts-lists -name '*.ts' -exec sed -i '' \
  's/errorResponse(409, "\([^"]*\)")/errorResponse(409, "CONFLICT", "\1")/g' {} +

# Update 500 errors (Internal Error)
find endpoints/moc-parts-lists -name '*.ts' -exec sed -i '' \
  "s/errorResponse(500, '\([^']*\)')/errorResponse(500, 'INTERNAL_ERROR', '\1')/g" {} +

find endpoints/moc-parts-lists -name '*.ts' -exec sed -i '' \
  's/errorResponse(500, "\([^"]*\)")/errorResponse(500, "INTERNAL_ERROR", "\1")/g' {} +

echo "✅ Response helpers updated (backup created at endpoints/moc-parts-lists.backup)"

# =============================================================================
# PHASE 4: API Gateway v2
# =============================================================================
echo ""
echo "📋 PHASE 4: API Gateway v2 Updates"
echo "-----------------------------------"

# Fix lambda-wrapper authorizer access
echo "Fixing core/utils/lambda-wrapper.ts..."

# These need manual review - just flag them
echo "⚠️  MANUAL FIXES NEEDED in core/utils/lambda-wrapper.ts:"
echo "   1. Line 67,79: Change 'event.requestContext.authorizer.claims'"
echo "      to 'event.requestContext.authorizer?.jwt?.claims'"
echo "   2. Lines 199,208,222: Add type guard before accessing statusCode"
echo "   3. Line 238: Add null check before spread operator"
echo ""

# Fix websocket connect
echo "⚠️  MANUAL FIX NEEDED in endpoints/websocket/connect/handler.ts:37:"
echo "   Change to: const token = event.queryStringParameters?.token"
echo ""

# =============================================================================
# PHASE 5: Cleanup Unused Variables
# =============================================================================
echo ""
echo "📋 PHASE 5: Cleanup Unused Variables"
echo "-------------------------------------"

echo "Removing unused imports and variables..."

# Remove unused pgTable import
sed -i '' '/import.*pgTable.*from/d' core/database/schema/umami.ts 2>/dev/null || true

# Prefix unused variables with underscore
sed -i '' 's/const durationMs =/const _durationMs =/g' core/observability/metrics.ts
sed -i '' 's/const uploadType =/const _uploadType =/g' core/utils/image-upload-service.ts

# Remove completely unused imports
sed -i '' '/import.*InternalServerError.*ApiError/d' core/observability/error-sanitizer.ts 2>/dev/null || true
sed -i '' '/import.*S3Client.*from/d' core/observability/tracing.ts 2>/dev/null || true
sed -i '' '/const isRetryable =/d' core/search/retry.ts 2>/dev/null || true
sed -i '' '/const getUserId =/d' core/utils/lambda-wrapper.ts 2>/dev/null || true
sed -i '' '/const ALLOWED_MIME_TYPES =/d' endpoints/moc-instructions/_shared/moc-file-service.ts 2>/dev/null || true
sed -i '' '/import.*uuidv4/d' endpoints/moc-instructions/upload-parts-list/handler.ts 2>/dev/null || true

echo "✅ Unused variables cleaned up"

# =============================================================================
# Verification
# =============================================================================
echo ""
echo "📊 Verification"
echo "==============="
echo "Running type check..."

pnpm tsc --noEmit 2>&1 | tee /tmp/api-errors-after-fixes.txt

ERROR_COUNT=$(grep "error TS" /tmp/api-errors-after-fixes.txt | wc -l | tr -d ' ')

echo ""
echo "===================="
echo "📈 Results:"
echo "===================="
echo "Errors remaining: $ERROR_COUNT"
echo ""

if [ "$ERROR_COUNT" -lt "50" ]; then
  echo "✅ Great progress! Over 50% errors fixed!"
elif [ "$ERROR_COUNT" -lt "80" ]; then
  echo "🟡 Good progress. Continue with manual fixes."
else
  echo "⚠️  Limited progress. Check script output for issues."
fi

echo ""
echo "Next steps:"
echo "1. Review ERROR_CATALOG.md for remaining manual fixes"
echo "2. Focus on highest-impact errors"
echo "3. Run 'pnpm tsc --noEmit' to see remaining errors"
echo ""
echo "Backup created at: endpoints/moc-parts-lists.backup"
echo "To restore: rm -rf endpoints/moc-parts-lists && mv endpoints/moc-parts-lists.backup endpoints/moc-parts-lists"
